export default [
  { en_name: 'Angola', cn_name: '安哥拉' },
  { en_name: 'Afghanistan', cn_name: '阿富汗' },
  { en_name: 'Albania', cn_name: '阿尔巴尼亚' },
  { en_name: 'Algeria', cn_name: '阿尔及利亚' },
  { en_name: 'Andorra', cn_name: '安道尔共和国' },
  { en_name: 'Anguilla', cn_name: '安圭拉岛' },
  { en_name: 'Antigua and Barbuda', cn_name: '安提瓜和巴布达' },
  { en_name: 'Argentina', cn_name: '阿根廷' },
  { en_name: 'Armenia', cn_name: '亚美尼亚' },
  { en_name: 'Ascension', cn_name: '阿森松' },
  { en_name: 'Australia', cn_name: '澳大利亚' },
  { en_name: 'Austria', cn_name: '奥地利' },
  { en_name: 'Azerbaijan', cn_name: '阿塞拜疆' },
  { en_name: 'Bahamas', cn_name: '巴哈马' },
  { en_name: 'Bahrain', cn_name: '巴林' },
  { en_name: 'Bangladesh', cn_name: '孟加拉国' },
  { en_name: 'Barbados', cn_name: '巴巴多斯' },
  { en_name: 'Belarus', cn_name: '白俄罗斯' },
  { en_name: 'Belgium', cn_name: '比利时' },
  { en_name: 'Belize', cn_name: '伯利兹' },
  { en_name: 'Benin', cn_name: '贝宁' },
  { en_name: 'Bermuda Is', cn_name: '百慕大群岛' },
  { en_name: 'Bolivia', cn_name: '玻利维亚' },
  { en_name: 'Botswana', cn_name: '博茨瓦纳' },
  { en_name: 'Brazil', cn_name: '巴西' },
  { en_name: 'Brunei', cn_name: '文莱' },
  { en_name: 'Bulgaria', cn_name: '保加利亚' },
  { en_name: 'Burkina Faso', cn_name: '布基纳法索' },
  { en_name: 'Burma', cn_name: '缅甸' },
  { en_name: 'Burundi', cn_name: '布隆迪' },
  { en_name: 'Cameroon', cn_name: '喀麦隆' },
  { en_name: 'Canada', cn_name: '加拿大' },
  { en_name: 'Cayman Is', cn_name: '开曼群岛' },
  { en_name: 'Central African Republic', cn_name: '中非共和国' },
  { en_name: 'Chad', cn_name: '乍得' },
  { en_name: 'Chile', cn_name: '智利' },
  { en_name: 'China', cn_name: '中国' },
  { en_name: 'Colombia', cn_name: '哥伦比亚' },
  { en_name: 'Congo', cn_name: '刚果' },
  { en_name: 'Cook Is', cn_name: '库克群岛' },
  { en_name: 'Costa Rica', cn_name: '哥斯达黎加' },
  { en_name: 'Cuba', cn_name: '古巴' },
  { en_name: 'Cyprus', cn_name: '塞浦路斯' },
  { en_name: 'Czech Republic', cn_name: '捷克' },
  { en_name: 'Denmark', cn_name: '丹麦' },
  { en_name: 'Djibouti', cn_name: '吉布提' },
  { en_name: 'Dominica Rep', cn_name: '多米尼加共和国' },
  { en_name: 'Ecuador', cn_name: '厄瓜多尔' },
  { en_name: 'Egypt', cn_name: '埃及' },
  { en_name: 'EI Salvador', cn_name: '萨尔瓦多' },
  { en_name: 'Estonia', cn_name: '爱沙尼亚' },
  { en_name: 'Ethiopia', cn_name: '埃塞俄比亚' },
  { en_name: 'Fiji', cn_name: '斐济' },
  { en_name: 'Finland', cn_name: '芬兰' },
  { en_name: 'France', cn_name: '法国' },
  { en_name: 'French Guiana', cn_name: '法属圭亚那' },
  { en_name: 'French Polynesia', cn_name: '法属玻利尼西亚' },
  { en_name: 'Gabon', cn_name: '加蓬' },
  { en_name: 'Gambia', cn_name: '冈比亚' },
  { en_name: 'Georgia', cn_name: '格鲁吉亚' },
  { en_name: 'Germany', cn_name: '德国' },
  { en_name: 'Ghana', cn_name: '加纳' },
  { en_name: 'Gibraltar', cn_name: '直布罗陀' },
  { en_name: 'Greece', cn_name: '希腊' },
  { en_name: 'Grenada', cn_name: '格林纳达' },
  { en_name: 'Guam', cn_name: '关岛' },
  { en_name: 'Guatemala', cn_name: '危地马拉' },
  { en_name: 'Guinea', cn_name: '几内亚' },
  { en_name: 'Guyana', cn_name: '圭亚那' },
  { en_name: 'Haiti', cn_name: '海地' },
  { en_name: 'Honduras', cn_name: '洪都拉斯' },
  { en_name: 'Hungary', cn_name: '匈牙利' },
  { en_name: 'Iceland', cn_name: '冰岛' },
  { en_name: 'India', cn_name: '印度' },
  { en_name: 'Indonesia', cn_name: '印度尼西亚' },
  { en_name: 'Iran', cn_name: '伊朗' },
  { en_name: 'Iraq', cn_name: '伊拉克' },
  { en_name: 'Ireland', cn_name: '爱尔兰' },
  { en_name: 'Israel', cn_name: '以色列' },
  { en_name: 'Italy', cn_name: '意大利' },
  { en_name: 'Ivory Coast', cn_name: '科特迪瓦' },
  { en_name: 'Jamaica', cn_name: '牙买加' },
  { en_name: 'Japan', cn_name: '日本' },
  { en_name: 'Jordan', cn_name: '约旦' },
  { en_name: 'Kampuchea (Cambodia )', cn_name: '柬埔寨' },
  { en_name: 'Kazakstan', cn_name: '哈萨克斯坦' },
  { en_name: 'Kenya', cn_name: '肯尼亚' },
  { en_name: 'Korea', cn_name: '韩国' },
  { en_name: 'Kuwait', cn_name: '科威特' },
  { en_name: 'Kyrgyzstan', cn_name: '吉尔吉斯坦' },
  { en_name: 'Laos', cn_name: '老挝' },
  { en_name: 'Latvia', cn_name: '拉脱维亚' },
  { en_name: 'Lebanon', cn_name: '黎巴嫩' },
  { en_name: 'Lesotho', cn_name: '莱索托' },
  { en_name: 'Liberia', cn_name: '利比里亚' },
  { en_name: 'Libya', cn_name: '利比亚' },
  { en_name: 'Liechtenstein', cn_name: '列支敦士登' },
  { en_name: 'Lithuania', cn_name: '立陶宛' },
  { en_name: 'Luxembourg', cn_name: '卢森堡' },
  { en_name: 'Madagascar', cn_name: '马达加斯加' },
  { en_name: 'Malawi', cn_name: '马拉维' },
  { en_name: 'Malaysia', cn_name: '马来西亚' },
  { en_name: 'Maldives', cn_name: '马尔代夫' },
  { en_name: 'Mali', cn_name: '马里' },
  { en_name: 'Malta', cn_name: '马耳他' },
  { en_name: 'Mariana Is', cn_name: '马里亚那群岛' },
  { en_name: 'Martinique', cn_name: '马提尼克' },
  { en_name: 'Mauritius', cn_name: '毛里求斯' },
  { en_name: 'Mexico', cn_name: '墨西哥' },
  { en_name: 'Moldova', cn_name: '摩尔多瓦' },
  { en_name: 'Monaco', cn_name: '摩纳哥' },
  { en_name: 'Mongolia', cn_name: '蒙古' },
  { en_name: 'Montserrat Is', cn_name: '蒙特塞拉特岛' },
  { en_name: 'Morocco', cn_name: '摩洛哥' },
  { en_name: 'Mozambique', cn_name: '莫桑比克' },
  { en_name: 'Namibia', cn_name: '纳米比亚' },
  { en_name: 'Nauru', cn_name: '瑙鲁' },
  { en_name: 'Nepal', cn_name: '尼泊尔' },
  { en_name: 'Netheriands Antilles', cn_name: '荷属安的列斯' },
  { en_name: 'Netherlands', cn_name: '荷兰' },
  { en_name: 'New Zealand', cn_name: '新西兰' },
  { en_name: 'Nicaragua', cn_name: '尼加拉瓜' },
  { en_name: 'Niger', cn_name: '尼日尔' },
  { en_name: 'Nigeria', cn_name: '尼日利亚' },
  { en_name: 'North Korea', cn_name: '朝鲜' },
  { en_name: 'Norway', cn_name: '挪威' },
  { en_name: 'Oman', cn_name: '阿曼' },
  { en_name: 'Pakistan', cn_name: '巴基斯坦' },
  { en_name: 'Panama', cn_name: '巴拿马' },
  { en_name: 'Papua New Cuinea', cn_name: '巴布亚新几内亚' },
  { en_name: 'Paraguay', cn_name: '巴拉圭' },
  { en_name: 'Peru', cn_name: '秘鲁' },
  { en_name: 'Philippines', cn_name: '菲律宾' },
  { en_name: 'Poland', cn_name: '波兰' },
  { en_name: 'Portugal', cn_name: '葡萄牙' },
  { en_name: 'Puerto Rico', cn_name: '波多黎各' },
  { en_name: 'Qatar', cn_name: '卡塔尔' },
  { en_name: 'Reunion', cn_name: '留尼旺' },
  { en_name: 'Romania', cn_name: '罗马尼亚' },
  { en_name: 'Russia', cn_name: '俄罗斯' },
  { en_name: 'Saint Lueia', cn_name: '圣卢西亚' },
  { en_name: 'Saint Vincent', cn_name: '圣文森特岛' },
  { en_name: 'Samoa Eastern', cn_name: '东萨摩亚(美)' },
  { en_name: 'Samoa Western', cn_name: '西萨摩亚' },
  { en_name: 'San Marino', cn_name: '圣马力诺' },
  { en_name: 'Sao Tome and Principe', cn_name: '圣多美和普林西比' },
  { en_name: 'Saudi Arabia', cn_name: '沙特阿拉伯' },
  { en_name: 'Senegal', cn_name: '塞内加尔' },
  { en_name: 'Seychelles', cn_name: '塞舌尔' },
  { en_name: 'Sierra Leone', cn_name: '塞拉利昂' },
  { en_name: 'Singapore', cn_name: '新加坡' },
  { en_name: 'Slovakia', cn_name: '斯洛伐克' },
  { en_name: 'Slovenia', cn_name: '斯洛文尼亚' },
  { en_name: 'Solomon Is', cn_name: '所罗门群岛' },
  { en_name: 'Somali', cn_name: '索马里' },
  { en_name: 'South Africa', cn_name: '南非' },
  { en_name: 'Spain', cn_name: '西班牙' },
  { en_name: 'SriLanka', cn_name: '斯里兰卡' },
  { en_name: 'St.Lucia', cn_name: '圣卢西亚' },
  { en_name: 'St.Vincent', cn_name: '圣文森特' },
  { en_name: 'Sudan', cn_name: '苏丹' },
  { en_name: 'Suriname', cn_name: '苏里南' },
  { en_name: 'Swaziland', cn_name: '斯威士兰' },
  { en_name: 'Sweden', cn_name: '瑞典' },
  { en_name: 'Switzerland', cn_name: '瑞士' },
  { en_name: 'Syria', cn_name: '叙利亚' },
  { en_name: 'Tajikstan', cn_name: '塔吉克斯坦' },
  { en_name: 'Tanzania', cn_name: '坦桑尼亚' },
  { en_name: 'Thailand', cn_name: '泰国' },
  { en_name: 'Togo', cn_name: '多哥' },
  { en_name: 'Tonga', cn_name: '汤加' },
  { en_name: 'Trinidad and Tobago', cn_name: '特立尼达和多巴哥' },
  { en_name: 'Tunisia', cn_name: '突尼斯' },
  { en_name: 'Turkey', cn_name: '土耳其' },
  { en_name: 'Turkmenistan', cn_name: '土库曼斯坦' },
  { en_name: 'Uganda', cn_name: '乌干达' },
  { en_name: 'Ukraine', cn_name: '乌克兰' },
  { en_name: 'United Arab Emirates', cn_name: '阿拉伯联合酋长国' },
  { en_name: 'United Kiongdom', cn_name: '英国' },
  { en_name: 'United States of America', cn_name: '美国' },
  { en_name: 'Uruguay', cn_name: '乌拉圭' },
  { en_name: 'Uzbekistan', cn_name: '乌兹别克斯坦' },
  { en_name: 'Venezuela', cn_name: '委内瑞拉' },
  { en_name: 'Vietnam', cn_name: '越南' },
  { en_name: 'Yemen', cn_name: '也门' },
  { en_name: 'Yugoslavia', cn_name: '南斯拉夫' },
  { en_name: 'Zimbabwe', cn_name: '津巴布韦' },
  { en_name: 'Zaire', cn_name: '扎伊尔' },
  { en_name: 'Zambia', cn_name: '赞比亚' }
]
