import enLocale from 'element-ui/lib/locale/lang/en'

export default {
  ...enLocale,
  控制面板: 'Control Panel',
  首页: 'Home',
  更新日志: 'Update Log',
  修改密码: 'Change password',
  员工列表: 'Staff List',
  员工: 'Employees',
  添加员工: 'Add Employee',
  修改资料: 'Modify information',
  员工组列表: 'Staff Group List',
  修改权限: 'Modify Permissions',
  客户: 'client',
  客户组: 'Customer Group',
  客户地址: 'Customer Address',
  代理管理: 'Agency Management',
  添加代理: 'Add Agent',
  修改代理: 'Modify Agent',
  计佣模版配置: 'Commissioning Template Configuration',
  佣金提现管理: 'Commission Withdrawal Management',
  佣金提现详情: 'Commission Withdrawal Details',
  佣金提现审核: 'Commission Withdrawal Audit',
  成交记录: 'Transaction Record',
  代理申请管理: 'Agent Application Management',
  未活跃提醒: 'Inactivity alerts',
  客户概览: 'Customer Overview',
  预报包裹列表: 'Forecast parcel list',
  订单: 'Orders',
  批量入库: 'Batch Entry',
  批量上架: 'Batch shelving',
  详情: 'Details',
  订单列表: 'Order List',
  无人认领包裹: 'Unclaimed packages',
  运费查询: 'Shipping Inquiry',
  审核: 'Audit',
  编辑: 'Edit',
  打包处理: 'Packing and processing',
  包裹订单概览: 'Parcel Order Overview',
  包裹快速入库: 'Fast parcel entry',
  货站: 'Goods station',
  发货单: 'Shipping Orders',
  拣货日志: 'Picking Log',
  物流查询: 'Logistics Inquiry',
  自定义物流轨迹: 'Customized Logistics Tracks',
  批量上传: 'Batch Upload',
  包裹快速合箱: 'Parcel fast closing',
  打包合箱: 'Packing and closing boxes',
  转运包裹管理: 'Transit Parcel Management',
  自提点: 'Self Pickup Point',
  自提点概览: 'Overview of pick-up points',
  路线: 'Route',
  配置: 'Configuration',
  销售价管理: 'Sales price management',
  模版: 'Template',
  渠道: 'Channels',
  新增: 'Add',
  添加路线: 'Add route',
  路线icon: 'Route icon',
  修改路线: 'Modify route',
  其余费用: 'Remaining costs',
  仓库地址配置: 'Warehouse address configuration',
  添加仓库: 'Add Warehouse',
  货位管理: 'Management of cargo space',
  修改仓库: 'Modify Warehouse',
  文章管理: 'Article Management',
  新增文章管理: 'Add article management',
  修改文章管理: 'Modify article management',
  文章管理的翻译内容: 'Translated content for article management',
  自提点配置: 'Self-pickup point configuration',
  添加自提点配置: 'Add pick-up point configuration',
  编辑自提点配置: 'Editorial pick-up point configuration',
  计佣方式配置: 'Commissioning method configuration',
  邮件通知配置: 'Email notification configuration',
  更多配置: 'More configurations',
  自动回复: 'Auto-reply',
  自定义菜单: 'Customized Menu',
  短信服务: 'Short Message Service',
  物流查询服务: 'Logistics Inquiry Service',
  邮件模版的翻译内容: 'Translated content of the email template',
  商品分类管理的翻译内容: 'Translation content of product category management',
  风险提示: 'Risk Warning',
  新增邮件模版: 'New Email Template',
  修改邮件模版: 'Modify Email Template',
  流水记录: 'Flow Records',
  财务: 'Finance',
  转账支付详情: 'Transfer payment details',
  在线支付详情: 'Online Payment Details',
  充值记录: 'Recharge Record',
  审核详情: 'Audit Details',
  充值审核: 'Recharge Audit',
  余额扣款处理: 'Balance deduction processing',
  财务概览: 'Financial Overview',
  自提点佣金结算: 'Pick-up point commission settlement',
  结算记录: 'Settlement records',
  订单财务审核: 'Order financial audit',
  成长值财务: 'Growth Value Finance',
  成长值财务详情: 'Growth Value Financial Details',
  代理佣金结算: 'Agency commission settlement',
  查看详细: 'View Details',
  代理结算: 'Agency billing',
  发票管理: 'Invoice Management',
  发票详情: 'Invoice details',
  会员体系: 'Membership System',
  营销管理: 'Marketing Management',
  用户福利: 'User Benefits',
  新增用户福利: 'New User Benefits',
  新用户送券: 'Free coupon for new users',
  被邀请人送券: 'Invitees send coupons',
  邀请新人送券: 'Invite newcomers to get coupons',
  抵用券管理: 'Coupon Management',
  投放记录: 'Placement records',
  添加抵用券: 'Add Credit Coupon',
  渠道管理: 'Channel Management',
  新增渠道管理: 'New Channel Management',
  修改渠道管理: 'Modify Channel Management',
  引流列表: 'Leads List',
  统计报表: 'Statistical Reports',
  广告图管理: 'Advertising map management',
  轮播图管理: 'Rotating image management',
  海报管理: 'Poster Management',
  页面广告管理: 'Page ad management',
  拼团管理: 'Group Management',
  团长管理: 'Mission Director Management',
  拼团配置: 'Grouping configuration',
  内容管理: 'Content Management',
  编辑内容: 'Editorial content',
  投诉建议: 'Complaint suggestions',
  客服中心: 'Customer Service Center',
  评价管理: 'Evaluation Management',
  公告管理: 'Announcement Management',
  新增公告: 'New Announcement',
  编辑公告: 'Editorial Announcement',
  公告管理的翻译内容: 'Translation content of announcement management',
  支持语言: 'Supported Languages',
  语言包: 'Language Packages',
  字符串翻译: 'String translation',
  栏目管理: 'Column Management',
  官网管理: 'Official Website Management',
  新增栏目: 'New column',
  编辑栏目: 'Editorial Column',
  '5天': '5 days',
  '7天': '7 days',
  '10天': '10 days',
  一级分类名称: 'First-class classification name',
  一键将预计体积重量设为实际体积重量: 'Set estimated volume weight to actual volume weight with one click',
  一键将预计重量改成实际重量: 'Set estimated volumetric weight to actual volumetric weight with one click',
  一键批量打包: 'One Click Batch Packing',
  一键结算: 'One Click Checkout',
  三级区域: 'Tertiary area',
  三边之和: 'Sum of three sides',
  上一页: 'Previous page',
  上传: 'Upload',
  上传图片: 'Upload images',
  上传成功: 'Upload successful',
  上传打包照片: '*Upload photos of the packaging',
  上传模版: 'Upload Template',
  上传照片: 'Upload photos',
  上架数量: 'Quantity on shelf',
  上架规则: 'Shelving rules',
  上级栏目: 'Parent column',
  下一步: 'Next step',
  下一页: 'Next page',
  下单人: 'Order Placeer',
  下单成交数: 'Number of orders placed',
  下单排行榜: 'Order Rank',
  下单支付最小满足金额: 'Place an order to pay the minimum satisfaction amount',
  下单数: 'Number of orders placed',
  下单是否需要身份证: 'Is ID required to place an order',
  下单返券: 'Coupon rebate on orders',
  下载: 'Download',
  下载二维码: 'Download QR Code',
  下载国家导入模板: 'Download Country Import Template',
  下载模版: 'Download Template',
  下载管理: 'Download Management',
  不再提示: 'No more tips',
  不启用保险: 'No insurance enabled',
  不启用关税: 'No tariff activation',
  不填写或填写数值为0代表不启用该条件: 'Not filled or filled with a value of 0 means the condition is not enabled',
  不开启: 'Not open',
  不开启多箱计价按总重量体积计算价格: 'Not open multi-case pricing by total weight volume calculation price',
  不推荐: 'Not recommended',
  不管数据有无更改点击保存后请务必重新操作总订单编辑保存以重新计算正确价格:
    'Regardless of whether the data has been changed or not, please make sure to rework the total order edit and save to recalculate the correct price',
  不能将不同用户的包裹合并打包: 'Cannot combine and pack packages from different users',
  不要求购买保险: 'No insurance required',
  不计算体积重: 'No volume weight calculation',
  不足: 'Not enough',
  与新用户送券同时开启时仅享受被邀请人券不勾选则两券共享:
    'If the coupon is opened at the same time with the new user, only the invitee coupon will be shared if the coupon is not checked.',
  专属小程序码: 'Exclusive applet code',
  且: 'and',
  业务域名: 'Business Domain',
  丢包预警: 'Packet loss warning',
  个: 'individual',
  个人: 'Personal',
  个人中心背景图片: 'Personal Center Background Image',
  个人信息: 'Personal Information',
  个人通关码: 'Personal clearance code',
  个分区: 'Zones',
  个包裹: 'Parcels',
  个已入库: 'One has been deposited',
  主色调1: 'Main color 1',
  主色调2: 'Main color 2',
  主菜单最多只能是三级: 'The main menu can only be up to three levels',
  主要用于计算包裹体积重量5000或6000如长高宽系数:
    'Mainly used to calculate package volume weight 5000 or 6000 such as length, height and width factors',
  二程物流信息: 'Two-way logistics information',
  二级分类名称: 'Secondary Classification Name',
  二级区域: 'Secondary area',
  二维码尺寸: 'QR code size',
  二维码尺寸不能为空: 'QR code size cannot be empty',
  交易类型: 'Transaction Type',
  交易金额: 'Transaction amount',
  亲爱的用户: 'Dear User',
  人数: 'Number of people',
  人民币: 'Chinese Yuan',
  仅保存: 'Save only',
  仅对多箱出库时生效关闭按统一的重量计算价格: 'Only valid for multi-case shipments when closing at a flat weight price',
  仅强制要求购买保险的订单启用: 'Only orders with mandatory insurance are enabled',
  仅强制要求购买关税的订单启用: 'Only orders with mandatory purchase duties are enabled',
  仅自提: 'Self-pickup only',
  仅送货上门: 'Home delivery only',
  仅首次下单返券: 'First order coupon only',
  今天: 'Today',
  仓位管理: 'Position Management',
  仓储期按自然日计算称重当日为仓储第一天: 'The storage period is calculated on the basis of natural days weighing the day of the first day of storage',
  仓库: 'Warehouse',
  仓库名字: 'Warehouse Name',
  仓库名称: 'Warehouse Name',
  仓库备注: 'Warehouse Remarks',
  仓库打包备注: 'Warehouse packing remarks',
  仓库背景图: 'Warehouse background image',
  付款方式: 'Payment Method',
  付款时间: 'Payment Time',
  代理: 'Agent',
  代理二维码: 'Agent QR Code',
  代理名称: 'Agent Name',
  代理成功提示图: 'Proxy Success Alert Chart',
  代理数: 'Number of agents',
  代理昵称: 'Agent nickname',
  代理概览: 'Agency Overview',
  代理用户: 'Agent Users',
  代理邀请客户成交金额排行榜: 'Agent Invitation Customer Transaction Amount Ranking',
  以上规则: 'The above rules',
  以下规则收费方式: 'The following rules charge the way',
  件数: 'Number of pieces',
  价值: 'Value',
  价格: 'Price',
  价格区间: 'Price range',
  价格模式: 'Price Model',
  价格类型: 'Price Type',
  价格表: 'Price List',
  价格表名称: '*Price List Name',
  价格设置需再在三个选项卡中配置: 'Price settings need to be configured in three more tabs',
  价格配置方式: 'Price Configuration Method',
  企业: 'Enterprise',
  企业地址: 'Business Address',
  企业微信: 'Enterprise WeChat',
  企业电话: 'Enterprise phone',
  优惠券名称: 'Coupon Name',
  优惠券类型: 'Coupon Type',
  会员名: 'Member Name',
  会员昵称: 'Member nickname',
  会员等级: 'Member Level',
  会员编号: 'Member Number',
  位置: 'Location',
  体积: 'Volume',
  体积总重量: 'Volume Total Weight',
  体积模式: 'Volume Mode',
  体积系数: 'Volume Factor',
  体积范围立方: 'Volume range cubic',
  体积范围立方米: 'Volume range cubic meter',
  体积计费: 'Volume billing',
  体积重: 'Volume weight',
  体积重大于实重时生效: 'Volume weight is effective when greater than the actual weight',
  体积重量: 'Volume weight',
  余额: 'Balance',
  余额支付: 'Balance Payment',
  作废: 'nullify',
  作废发票: 'Voided Invoice',
  作废日志: 'Voiding Log',
  作废申请: 'Revocation request',
  作废订单: 'Voided Orders',
  佣金: 'Commissions',
  佣金分成: 'Commission Share',
  佣金总数: 'Total Commissions',
  佣金报表: 'Commission Statement',
  佣金比例: 'Commission Percentage',
  佣金金额: 'Commission amount',
  佣金金额提现: 'Withdrawal of commission amount',
  使用已有账户登录: 'Login with existing account',
  使用数量: 'Number of uses',
  使用时间: 'Time of use',
  使用积分: 'Points used',
  使用范围: 'Use range',
  例512工作日日: 'Example 512 working days',
  例周一至周六08002000: 'Example: Monday to Saturday 08002000',
  例生成价格表样式如下时: 'Example of a price list generated in the following style',
  保价类型: 'Price Guarantee Type',
  保存: 'Save',
  保存并发布: 'Save and publish',
  保存并提交: 'Save and submit',
  保存成功: 'Save successfully',
  保存排序结果: 'Save Sort Results',
  保持登录: 'Stay logged in',
  保险服务: 'Insurance Services',
  保险说明: 'Insurance Description',
  保险费用: 'Insurance Costs',
  保险金额: 'Insurance amount',
  信息: 'Information',
  修改: 'Modify',
  修改团单信息: 'Modify group order information',
  修改客户组: 'Modify customer group',
  修改密码成功: 'Modify password successfully',
  修改物流信息: 'Modify logistics information',
  修改状态: 'Modify status',
  修改货位: 'Modify cargo space',
  倒计时: 'Countdown time',
  值: 'Value',
  值点击修改: 'Value click to modify',
  假设计费重量为: 'Assuming that the billing weight is',
  停止支持该国家后再次开启时需重新添加支持仓库与路线:
    'When you stop supporting the country and turn it on again, you need to add the supported depots and routes again',
  允许登录: 'Login allowed',
  允许自提点页面编辑公告: 'Allow editing of announcements on the pick-up point page',
  充值: 'Recharge',
  充值收入: 'Recharge income',
  充值方式: 'Recharge Method',
  充值赠送: 'Recharge Gift',
  充值金额: 'Recharge Amount',
  免抛条件: 'Free throwing condition',
  免费仓储期天: 'Free storage period days',
  入库: 'Storage',
  入库信息: 'Storage Information',
  入库尺寸: 'Storage Size',
  入库日志: 'Inbound Log',
  入库时间: 'Storage time',
  入库是否必填尺寸: 'Required Size',
  入库是否必填货位: 'Whether the incoming goods are required to be stored',
  入库照片: 'Inbound Photo',
  入库重量: 'Inbound weight',
  入门教程: 'Getting Started Tutorial',
  全团已提交: 'The whole group has been submitted',
  全年: 'Full year',
  全抛: 'Full Throw',
  全部: 'All',
  全部显示: 'Show all',
  全部货到付款: 'All Cash on Delivery',
  公众号二维码: 'Public number two-dimensional code',
  公众号菜单主菜单最多只能是三级每级主菜单最多可以有五个子菜单栏目:
    '*Public menu main menu can only be a maximum of three levels each level of the main menu can have a maximum of five sub-menu columns',
  公众号配置: 'Public Configuration',
  公司: 'Company',
  公告: 'Announcement',
  公告标题: '*Announcement Title',
  公告标题不超过30个字: 'Announcement title no more than 30 words',
  公告设置: 'Announcement Settings',
  公告详情: '*Announcement details',
  公开: 'Public',
  公开拼团团长: 'Public group leader',
  关: 'close',
  关于我们: 'About Us',
  关税服务: 'Tariff Service',
  关税说明: 'Tariff Description',
  关税费用: 'Tariff Fees',
  关税金额: 'Tariff Amount',
  关联公众号文章: 'Affiliated Public Articles',
  关联单号: 'Affiliate Order Number',
  关联订单号: 'Affiliate Order Number',
  关键词: 'Keyword',
  关键词回复: 'Keyword Reply',
  关闭: 'Close',
  关闭两券共享: 'Close two coupon sharing',
  关闭其他: 'Close Other',
  关闭所有: 'Close all',
  其他配置: 'Other Configurations',
  其它方式: 'Other way',
  具体操作: 'Specific operation',
  内容: 'Content',
  内容介绍: 'Content Introduction',
  内容详情: '*Content details',
  出库: 'Out of storage',
  出库方式: 'Out of storage method',
  出库箱数: 'Number of boxes',
  出箱类型: 'Out of the box type',
  分享: 'Share',
  分享链接自定义图片: 'Share link custom image',
  分区: 'Partition',
  分区名称: 'Partition Name',
  分区数量: 'Number of Sections',
  分区类型: 'Partition Type',
  分区表: 'Partition Table',
  分区表中设置不同区域分组: 'Setting up different area groups in the "Partition Table"',
  分区表名称: 'Partition Table Name',
  分成方式: 'Dividing method',
  分箱模版下载: 'Divided box template download',
  分类: 'Classification',
  分类名称: '*Classification name',
  分组: 'Division group',
  分配客服: 'Assign customer service',
  分配销售: 'Assign sales',
  列数: 'Number of columns',
  创建人: 'Created by',
  创建发货单: 'Create Shipping Order',
  创建日期: 'Creation Date',
  创建时间: 'Creation Time',
  删除: 'Delete',
  删除回复: 'Delete Reply',
  到账之日起计算有效期为: 'The validity period is calculated from the date of arrival',
  到账时间: 'Arrival time',
  到达目的地后再进行支付: 'Pay when you arrive at your destination',
  刷新: 'Refresh',
  券包: 'Voucher Pack',
  券名称: 'Voucher Name',
  券总量: 'Total number of coupons',
  券最大上限金额: 'Maximum amount of coupons',
  券码: 'Coupon Code',
  券金额方式: 'Coupon Amount Method',
  前往下载: 'Go to download',
  前缀字符: 'Prefix character',
  剩余时间: 'Remaining time',
  加入发货单: 'Add to shipping order',
  加密方式: 'Encryption method',
  包含的包裹: 'Included packages',
  包裹: 'Package',
  包裹价值: 'Parcel Value',
  包裹入库: 'Parcel Inbound',
  包裹列表: 'Parcel List',
  包裹单号: 'Parcel Order Number',
  包裹号: 'Parcel number',
  包裹图片: 'Parcel picture',
  包裹增值服务: 'Parcel Value Added Service',
  包裹实际重量: 'Parcel Actual Weight',
  包裹对比: 'Parcel Comparison',
  包裹尺寸为商品打包后实际包裹箱的长宽高用于某些体积重量的线路运费计算:
    'The package size is the length, width and height of the actual parcel box after the goods are packed for certain volume weight line freight calculation',
  包裹尺寸选填: 'Package Size（Optional）',
  包裹总价值: 'Total value of parcels',
  包裹总数: 'Total number of parcels',
  包裹数: 'Number of parcels',
  包裹数与件数: 'Number of parcels and pieces',
  包裹数量: 'Number of parcels',
  包裹未找到: 'Package not found',
  包裹概览: 'Parcels Overview',
  包裹清单: 'Package List',
  包裹状态: 'Package Status',
  包裹统计: 'Parcel Statistics',
  包裹编码: 'Package Code',
  包裹详情: 'Package Details',
  包裹重量: 'Package weight',
  包裹重量不足最小: 'Parcel weight less than min',
  包裹重量向上取值: 'Parcel weight up take',
  包裹预报: 'Parcel Forecast',
  包裹预警: 'Parcel Alert',
  区: 'Zone',
  区号: 'Zone Number',
  区块名: 'Block name',
  区块详情: 'Block Details',
  区块说明: 'Block Description',
  区域: 'Area',
  区域编号: 'Zone Number',
  区间: 'Zone',
  半抛: 'Half Throw',
  协议背景图片: 'Protocol background image',
  单: 'single',
  单个客户投放: 'Single customer placement',
  单人限领数量: 'Single limit number of claims',
  单价: 'Single price',
  单位体积立方: 'Unit volume cubic',
  单位实际重量固定费用: 'Fixed cost per unit of actual weight',
  单位续重: 'Unit weight renewal',
  单位计费重量固定费用: 'Unit billing weight fixed fee',
  单位配置: 'Unit configuration',
  单位重量: 'Unit weight',
  单位金额: 'Unit Amount',
  单号查询: 'Unit Number Search',
  单号规则: 'Unit Number Rules',
  单号追踪: 'Unit number tracking',
  单号长度: 'Unit number length',
  单箱: 'Single box',
  单箱出库: 'Single box out',
  单箱固定费用: 'Single box fixed fee',
  单箱限重: 'Single box weight limit',
  单箱限长: 'Single box limit length',
  单篇文章: 'Single article',
  单边长度: 'Single side length',
  单选: 'single selection',
  单页: 'Single Page',
  单页详情: 'Single Page Details',
  单页链接: 'Single Page Link',
  原始上传清单: 'Original upload list：',
  原始商品备注: 'Original product notes：',
  原始商品数量: 'Original product quantity：',
  原密码: 'Original password',
  原版官网: 'Original website',
  原箱出库: 'Original box out of the warehouse',
  原路返回: 'Original way back',
  去注册: 'Go to registration',
  去登录: 'Go to login',
  去配置: 'Go to configuration',
  参团详情: 'Tour Details',
  参数: 'Parameters',
  参考时效: 'Reference time limit',
  发件人名称: 'Sender Name',
  发件人密码: "Sender's password",
  发件人用户名: 'Sender User Name',
  发件人邮件: "Sender's email",
  发布人员: 'Poster',
  发布时间: 'Posting Time',
  发票: 'Invoice',
  发票号码: 'Invoice Number:',
  发票抬头: 'Invoice payable to',
  发票类型: 'Invoice Type',
  发票金额: 'Invoice Amount',
  发货: 'Invoice',
  发货单单号: 'Shipping Order Number',
  发货单号: 'Shipping Order Number',
  发货单名称: 'Shipping Order Name',
  发货开始日期: 'Shipping Start Date',
  发货快递公司: 'Shipping courier company',
  发货时间: 'Shipping Time',
  发货结束日期: 'End date of shipment',
  发送时间: 'Sending time',
  发送通知: 'Shipping Notification',
  取消: 'Cancel',
  取消包裹重量限制: 'Eliminate parcel weight limit',
  取消发货: 'Cancel Shipping',
  取消拼团: 'Cancel Grouping',
  取消拼团后团员已提交的拼团包裹将会退回原仓库您确定要取消该拼团吗:
    'Cancellation of the group will result in the return of the submitted package to the original warehouse Are you sure you want to cancel the group?',
  取消精选: 'Cancel Featured',
  可以同时发两条消息: 'You can send two messages at the same time',
  可在此界面设置渠道专用增值服务如加固费打包费保价费偏远地区配送费等:
    'You can set up channel-specific value-added services in this interface, such as reinforcement fee, packaging fee, price guarantee fee, remote area delivery fee, etc.',
  可导出价格表批量修改后再导入表格: 'Price list can be exported for batch modification and then imported into the table',
  可得佣金: 'Commissions available￥',
  可获佣金: 'Commissions available',
  号码: 'Number',
  合并规则: 'Consolidation Rules：',
  合计: 'Total:',
  合计已提交包裹: 'Total Submitted Parcels：',
  合计税款: 'Total Taxes',
  合计金额: 'Total Amount',
  同时收取: 'Collected at the same time',
  同时满足以下条件: 'The following conditions are met at the same time',
  名称: 'Name',
  名称不能为空: 'Name cannot be empty',
  后台投放不计入总数: 'Backend placement is not counted in the total',
  向上取值: 'Upward value',
  否: 'No',
  启用: 'Enabled',
  启用保险: 'Enable Insurance',
  启用关税: 'Enable Tariff',
  启用国家地区: 'Enabling countries/Region',
  启用国家地区总数量: 'Enabling countries/Total number of regions',
  启用成长值: 'Enable Growth Value',
  启用积分: 'Enable Points',
  员工组: 'Employee Group',
  员工组中文名: 'Staff Group Chinese Name',
  员工组英文名: 'Staff Group English Name',
  品牌: 'Brand',
  品牌名称: 'Brand Name',
  唤醒: 'Awakening',
  商品价值: 'Commodity value',
  商品信息: 'Commodity Information',
  商品分类: 'Commodity classification',
  商品分类管理: 'Commodity classification management',
  商品名称: 'Commodity name',
  商品数量: 'Quantity',
  商品清单: 'Product list',
  回复内容: 'Reply content',
  回复类型: 'Response type',
  团员: 'Member',
  团员自付: 'Group members pay for themselves',
  团购: 'Group purchase',
  团长: 'Group leader',
  团长代付: 'Group Leader Paid for',
  固定金额: 'Fixed amount',
  国内: 'Domestic',
  国家: 'Country',
  国家地区: 'Country Area',
  国家邮编: 'Country Postcode',
  国际: 'International',
  国际短信剩余次数: 'International SMS Remaining Times',
  国际短信服务: 'International SMS Service',
  图标: 'Icon',
  图片: 'Pictures',
  图片一: 'Image one',
  图片二: 'Image two',
  在12步骤完成后系统生成空白价格表在价格表中配置具体价格:
    'After steps 1 and 2 are completed, the system generates a blank "price list" and configures specific prices in the price list',
  在仓库打包完成后再进行支付: 'Payments will be made after packing is completed at the warehouse',
  在满足免抛条件情况下不考虑体积重仅以实重计费: 'In the case of meeting the conditions of free throwing, only the actual weight is charged without considering the volume weight',
  在线支付: 'Online Payment',
  地图选点: 'Map selection',
  地址: 'Address',
  地域通知管理: 'Geographical notification management',
  城市: 'City',
  域名: 'Domain Name',
  基价: 'Base Price',
  基本信息: 'Basic Info',
  基本资料: 'Basic Information',
  基础信息: 'Basic Info',
  基础配置: 'Basic Configuration',
  增值服务: 'Value-added Services',
  增值服务名称: 'Value-added Service Name',
  增值服务费: 'Value-added Service Fee',
  增值服务金额: 'Value-added Service Amount',
  增值费用名称: 'Value-added fee name',
  增值费用名称多语言: 'Value-added Fee Name（Multilingual）',
  增加: 'Add',
  处理: 'Processing',
  处理中: 'Processing in progress',
  处理人: 'Processor',
  处理时间: 'Processing time',
  备案号: 'Record number',
  备注: 'Remark',
  备注截图: 'Remark screenshot',
  备用图片1: 'Alternate picture 1',
  备用图片2: 'Alternate picture 2',
  备用图片3: 'Alternate picture 3',
  备用图片4: 'Alternate image 4',
  复制: 'Copy',
  复制价格表: 'Copy price list',
  复制单号: 'Copy order number',
  复制成功: 'Copy Success',
  复制路线: 'Copy route',
  外部交易号: 'External transaction number',
  外部链接: 'External links',
  多个包裹单号请用回车分割: 'Multiple parcel numbers, please use the carriage return to split',
  多箱: 'Multi-case',
  多箱出库: 'Multi-case outbound',
  多箱出库按多箱重量计价: 'Multi-case shipments are priced at multi-case weight',
  多箱出库最小重量: 'Minimum weight of multiple cases out of storage',
  多箱出库计价方式: 'Multi-case dispatch pricing method',
  多箱单独计算价格后相加为总价: 'Multiple boxes are priced separately and added together for a total price',
  多箱单独计算计费重量重量体积相加后计算价格: 'Separate billing weight for multiple cases(Weight / Calculate the price after adding up the volume)',
  多箱单独计算计费重量后向上取值计算价格:
    'Separate billing for multiple boxes Weight(Weight/After volume aggregation，The sum is taken upwards to calculate the price)',
  多篇文章: 'Multi-article',
  多级续重模式: 'Multi-level renewal weight model',
  多级首重续重模式: 'Multi-level first weight renewal mode',
  多选: 'Multiple Choice',
  大于: 'greater than',
  大于等于: 'Greater than or equal to',
  大陆短信剩余次数: 'Continental SMS remaining times',
  大陆短信服务: 'Continental SMS Service',
  天: 'days',
  失效时间: 'Expiration time',
  失败: 'Failure',
  头程物流信息: 'Headway Logistics Information',
  如有合箱操作请勿填写此项填入实际尺寸即可: 'If there is a combined box operation, please do not fill in this fill in the actual size can',
  姓名: 'Name',
  子栏目名称: 'Subfield Name',
  字符串: 'String',
  字符串1: 'String 1',
  字符串2: 'String 2',
  存放货位: 'Storage space',
  完成: 'Completed',
  完成订单数: 'Number of completed orders',
  官网: 'official website',
  实付: 'Paid',
  实付费用: 'Actual cost',
  实重: 'Actual weight',
  实际体积重量: 'Actual volume weight',
  实际尺寸: 'Actual Size',
  实际总重量: 'Actual total weight',
  实际支付: 'Actual Payment',
  实际支付金额: 'Actual amount paid',
  实际费用: 'Actual Cost',
  实际运费: 'Actual Shipping Cost',
  实际重量: 'Actual weight',
  实际重量与体积重量两者取大: 'The greater of actual weight and volume weight',
  审核中: 'Auditing in progress',
  审核人员: 'Auditors',
  审核备注: 'Audit Remarks',
  审核并支付: 'Reviewed and paid',
  审核拒绝: 'Audit Rejected',
  审核拒绝信息: 'Audit Rejected Information',
  审核时间: 'Audit time',
  审核状态: 'Audit Status',
  审核通过: 'Audit Passed',
  审核通过信息: 'Audit passed information',
  客户信息: 'Customer Information',
  客户合并: 'Customer Merge',
  客户图片: 'Customer picture',
  客户备注: 'Customer Notes',
  客户头像: 'Customer avatar',
  客户截图: 'Customer Screenshot',
  客户昵称: 'Customer Nickname',
  客户登录配置: 'Customer Login Configuration',
  客户签收: 'Customer sign-in',
  客户组中文名: 'Customer Group Chinese Name',
  客户组投放: 'Customer Group Placement',
  客户组描述: 'Customer group description',
  客户组英文名: 'Customer Group English Name',
  客户编号: 'Customer Number',
  客户订单支付成功后即可返券: 'Coupon rebate after successful payment of customer order',
  客服备注: 'Customer Service Remarks',
  客服评分: 'Customer Service Rating',
  宣传语: 'Promotion language',
  宽: 'wide',
  寄往仓库: '*Send to warehouse',
  寄往国家: 'Ship to country',
  寄往地区: 'Send to area',
  密码: 'Password',
  密钥: 'Key',
  对比: 'Compare',
  导入: 'Import',
  导入数据: 'Import Data',
  导出: 'Export',
  导出发票: 'Export Invoice',
  导出清单: 'Export List',
  导出清单含包裹信息: 'Export List（Contains package information）',
  封面图: 'Cover image',
  小于: 'Less than',
  小于等于: 'Less than or equal to',
  小程序: 'Applet',
  小程序码: 'Applet code',
  小程序运费查询页图: 'Small program shipping inquiry page diagram',
  小程序配置: 'Applet Configuration',
  小程序链接: 'Applet Link',
  小程序页面路径: 'Applet page path',
  小程序预报页图: 'Small program forecast page map',
  小程序首页视频入口图: 'Applets home page video entrance map',
  小程序首页评论入口图: 'Applet home page comment entrance map',
  小计: 'Subtotal',
  尺寸: 'Size',
  尺寸长宽高: 'Size（Length Width Height）',
  层数: 'Number of layers',
  属性名称: 'Attribute name',
  左开右闭: 'Left open and right closed',
  左闭右开: 'Left closed and right open',
  已付款: 'Paid',
  已作废: 'Voided',
  已使用数量: 'Quantity used',
  已入库: 'Stocked',
  已入库包裹: 'Inbound packages',
  已出库: 'Out of storage',
  已到自提点: 'Pick-up point',
  已发货: 'Shipped',
  已发货包裹: 'Shipped Package',
  已发货通知: 'Shipped Notice',
  已处理: 'Processed',
  已失效: 'Expired',
  已完成: 'Completed',
  已完成订单: 'Completed Orders',
  已审核: 'Reviewed',
  已开票: 'Invoiced',
  已打包: 'Packed',
  已拣货包裹: 'Packages Picked',
  已提交: 'Submitted',
  已提现: 'Withdrawn',
  已支付: 'Paid',
  已收货: 'Received',
  已签收: 'Signed for',
  已结算: 'Cleared',
  已结算佣金: 'Commissions cleared',
  已集包: 'Collected packages',
  市: 'City',
  帮助中心: 'Help Center',
  常见问题: 'FAQ',
  序号: 'Serial number',
  应付: 'Payable',
  应付费用总计: 'Total Fees Payable',
  应付金额: 'Amount Payable',
  应用: 'Applications',
  应用内跳转: 'Intra-Application Jump',
  应用分区: 'Application Partitions',
  应用数量: 'Number of Applications',
  底栏: 'Bottom column',
  延长拼团时间: 'Extend the collocation time',
  建议尺寸: 'Recommended Size',
  建议添加35条链接限制最多添加10条链接: 'Suggest adding 3～5 links（Limit adding up to 10 links）',
  开: 'Open',
  开启: 'Open',
  开启仅登录状态可分享领券: 'Enable shareable coupons for login status only：',
  开启仓库限制: 'Enable warehouse restrictions',
  开启体积重: 'Enable volume weight',
  开启后若预报包裹超过设定时间未入库将会在包裹列表进行提示表示包裹有丢失风险:
    'After opening, if the forecasted parcels are not warehoused for more than the set time, they will be prompted in the parcel list, indicating that the parcels are at risk of being lost',
  开启拼团: 'Open grouping',
  开启显示宣传语: 'Turn on display of tagline',
  开启显示用户名称: 'Turn on display of user name',
  开启用户头像: 'Enable user avatar',
  开启短信登录验证: 'Enable SMS login verification',
  开启线路: 'Open line',
  开启表示需要提供收件人清关编码: 'Open to indicate the need to provide the recipient clearance code。',
  开启邮箱登录验证: 'Enable mailbox login verification',
  开始日期: 'Start Date',
  开始时间: 'Start time',
  开户银行: 'Bank of account opening',
  开票信息: 'Invoicing information',
  开票备注: 'Invoicing Remarks',
  开票完成: 'Invoicing completed',
  开票明细: 'Invoicing details',
  开票金额: 'Invoicing amount:',
  开闭区间选择: 'Opening and closing interval selection',
  异常件: 'Abnormal piece',
  异常件原因: 'Reason for abnormal pieces',
  弃件: 'Abandonment',
  弃件包裹: 'Abandoned package',
  弃件原因: 'Reason for abandoned package',
  张三: 'Zhang San',
  强制收取: 'Forced collection',
  当前: 'Current',
  当前操作暂无权限: 'No permission for current operation',
  当前用户没有可打包的包裹: 'The current user has no packable packages',
  当前限制上传1个文件: 'Current limit upload 1 file',
  当前页面配置的地址为用户发往仓库的真实收件地址请填写有效准确的信息请不要填写座机:
    'The address configured on the current page is the real recipient address sent to the warehouse by the user, please fill in valid and accurate information, please do not fill in the landline',
  当包裹重量不足最小重量时按最小重量来计算: 'When the weight of the package is less than the minimum weight, the minimum weight will be calculated',
  当您为仓库添加了货位系统会自动分配货位同时您也可以自定义填写货位:
    'When you add cargo space for the warehouse system will automatically assign cargo space at the same time you can also custom fill in the cargo space',
  彻底删除: 'Delete completely',
  待入库包裹: 'Pending incoming packages',
  待发货: 'Pending shipments',
  待发货订单: 'Pending Shipping Orders',
  待取件通知: 'Pending Pickup Notification',
  待处理: 'Pending',
  待处理投诉: 'Pending Complaints',
  待审核: 'Pending Review',
  待审核付款: 'Pending Payment Review',
  待打包订单: 'Pending order packing',
  待提交: 'Pending submission',
  待提现: 'Pending cash withdrawals',
  待支付: 'Pending payment',
  待结算: 'Pending settlement',
  微信号: 'Micro Signal',
  微信扫码请点击打开页面右上角选择在浏览器中打开或直接使用浏览器扫码:
    'WeChat sweep code, please click to open the upper right corner of the page and choose to open in the browser or directly use the browser sweep code',
  微信支付: 'WeChat Payment',
  微信昵称: 'WeChat Nickname',
  忘记密码: 'Forget password',
  快递100剩余次数: 'Courier 100 remaining times',
  快递100查询: 'Express 100 inquiry',
  快递100查询剩余次数: 'Courier 100 query remaining times',
  快递100配置: 'Express 100 configuration',
  快递公司: 'Express company',
  快递公司代码: 'Express company code',
  快递公司名称: 'Express company name',
  请输入快递公司名称: 'Please enter the name of the courier company',
  请输入快递公司代码: 'Please enter the courier company code',
  请输入排序索引: 'Please enter the sort index',
  快递单号: '*Express order number',
  快递单号不存在或客户未预报请确认是否入库: 'The courier bill number does not exist or the customer does not forecast please confirm whether the inventory',
  快递方式: 'Courier method',
  快速下单: 'Quick order',
  快速下单无需合箱: 'Quick order (no need to combine boxes)',
  快速出库: 'Fast Outbound',
  快速合箱: 'Fast Case Consolidation',
  快速收货: 'Fast Receiving',
  快速签收: 'Quick Sign-Off',
  忽略地址精确度检查: 'Ignore address accuracy checks',
  总价: 'Total Price',
  总体积属于哪一个区间即按照该区间价格计算总价: 'The total volume belongs to which range is the total price calculated according to the price of that range',
  总包裹量: 'Total parcel volume',
  总发货单数: 'Total number of shipping orders',
  总实际重量: 'Total actual weight',
  总收入: 'Total Revenue',
  总用户: 'Total Users',
  总计: 'Total',
  总订单: 'Total Orders',
  总费用: 'Total Cost',
  总重量: 'Total weight',
  总重量属于哪一个区间即按照该区间价格计算总价: 'The total weight belongs to the range that the total price is calculated according to the price of that range',
  总量: 'Total volume',
  总金额: 'Total amount￥',
  恢复: 'Recovery',
  恢复申请: 'Resume application',
  您可以在这里估算运费请在左边输入相关参数: 'You can estimate shipping costs here Please enter the relevant parameters on the left',
  您当前未开启物流查询: 'You are not currently open for logistics inquiries',
  您当前未开启短信服务: 'You currently do not have SMS service turned on',
  您当前正在使用第三方物流查询服务: 'You are currently using a third party logistics inquiry service',
  您当前正在使用第三方短信服务: 'You are currently using a third party SMS service',
  您当前正在使用系统内物流查询: 'You are currently using the system logistics query',
  您当前正在使用系统内短信服务: 'You are currently using the in-system SMS service',
  您当前选择了: 'You currently have selected',
  您是否已确认佣金申请结算吗: 'Have you confirmed the commission request settlement?',
  您是否确认将该包裹退回未入库状态: 'Do you confirm to return the package to the unstocked status',
  您是否确认批量删除: 'Do you confirm the bulk deletion of',
  您是否确认批量删除如果是批量删除二级地址的话该分级下所有的三级地址也会删除:
    'Do you confirm the batch deletion if the batch deletion of secondary addresses then all tertiary addresses under the hierarchy will also be deleted',
  您是否确认按区域编号自动排序: 'Do you confirm automatic sorting by area code',
  您本次选择: 'You choose this time',
  您的改价操作记录将会保存在日志记录中: '*A record of your price change will be saved in the log.',
  您真的确认批量结算吗: 'Are you really sure about bulk billing?',
  您真的确认更改状态为已付款吗: 'Did you really confirm the status change to Paid?',
  您真的确认更改状态为已签收吗: 'Did you really confirm that the change status was signed for?',
  您真的确认要一键结算吗: 'Are you really sure you want one-click billing?',
  您真的要删除发货单吗: 'Do you really want to delete a shipping order?',
  您真的要删除吗: 'Do you really want to delete it?',
  您真的要删除增值服务吗: 'Do you really want to remove value-added services?',
  您真的要删除此仓库吗: 'Do you really want to delete this repository?',
  您真的要删除此代理: 'Do you really want to delete this agent?',
  您真的要删除此菜单: 'Do you really want to delete this menu?',
  您真的要删除此规则: 'Do you really want to remove this rule?',
  您真的要删除此货位吗: 'Do you really want to delete this space?',
  您真的要删除此路线: 'Do you really want to delete this route?',
  您真的要删除此路线吗: 'Do you really want to delete this route?',
  您真的要删除物品属性吗会影响到系统内的包裹请谨慎操作:
    'Do you really want to remove item attributes? will affect the system within the Packages，Please proceed with caution。',
  您真的要删除转账支付吗: 'Do you really want to remove transfer payments?',
  您真的要删除这个包裹吗: 'Do you really want to delete this package?',
  您真的要发货吗: 'Do you really want to ship?',
  您真的要取消发货吗: 'Do you really want to cancel the shipment?',
  您真的要审核拒绝吗: 'Do you really want to review the rejection?',
  您真的要彻底删除: 'Do you really want to delete it completely?',
  您真的要恢复包裹吗: 'Do you really want to restore the package?',
  您真的要执行此操作吗: 'Do you really want to perform this operation?',
  您真的要批量发送通知吗: 'Do you really want to send bulk notifications?',
  您真的要批量改成货到付款吗: 'Do you really want to change to cash on delivery in bulk?',
  您真的要移除发货单吗: 'Do you really want to remove the shipping order?',
  您真的要设为默认吗: 'Do you really want to set it as default?',
  您确定提交该拼团吗: 'Are you sure you want to submit this group?',
  您确认要恢复该开票申请吗: 'Are you sure you want to resume this invoicing request?',
  您确认进行出库吗: 'Are you sure you want to make an exit?',
  您确认进行收货吗: 'Do you confirm receipt of goods?',
  成交支付金额比例: 'The percentage of the payment amount of the transaction',
  成交数: 'Number of transactions',
  成交数量: 'Number of transactions',
  成交时间: 'Transaction time',
  成交订单数: 'Number of orders',
  成交金额: 'Deal amount',
  成交金额元: 'Deal amount(yuan)',
  成功: 'Success',
  成功操作: 'Successful operation',
  成员: 'Members',
  成员数量: 'Number of members',
  成本价格: 'Cost Price',
  成长值: 'Growth Value',
  成长说明: 'Growth Description',
  或: 'or',
  截止: 'Cutoff',
  截止重量: 'Cut-off weight',
  所属仓库: 'Warehouse',
  所属代理: 'Agent',
  所属包裹: 'Parcel',
  所属发货单: 'Shipping Order',
  所属发货号: 'Shipment number',
  所属员工组: 'Employee group',
  所属国家地区: 'Country and region',
  所属客服: 'Customer Service',
  所属订单: 'Order',
  所属订单号: 'Order number',
  所属路线: 'Route',
  所属销售: 'Affiliated Sales',
  所有用户: 'All users',
  所有规则最高收费: 'All rules maximum charge',
  所有边长: 'All side lengths',
  手机号: 'Cell phone number',
  手机号不能为空: 'Cell phone number cannot be empty',
  手机号激活: 'Mobile number activation',
  手机号码: 'Mobile phone number',
  手机联系电话: 'Cell phone contact number',
  打包: 'Packing',
  打包图片: 'Packing picture',
  打包照片: 'Packing Photos',
  打包状态: 'Packing status',
  打包自动生成货到付款订单: 'Packing automatic generation of cash on delivery orders',
  打包评分: 'Package rating',
  打包详情: 'Package Details',
  打包详细: 'Packing details',
  打印标签: 'Print Label',
  打印面单地址: 'Print Face Sheet Address',
  扣款: 'Chargeback',
  扣款备注: 'Chargeback Comments',
  扣款金额: '*Amount deducted',
  批次号: 'Batch number',
  批量出库: 'Batch Out',
  批量删除: 'Batch delete',
  批量发送通知: 'Batch send notification',
  批量唤醒: 'Batch wakeup',
  批量导入: 'Batch Import',
  批量收货: 'Batch Receive',
  批量改支付方式: 'Change payment method in bulk',
  批量更改支付方式: 'Batch change payment method',
  批量更新单号: 'Batch update single number',
  批量更新单号二程: 'Batch update single number two course',
  批量签收: 'Batch sign-off',
  批量结算: 'Batch settlement',
  批量集包: 'Batch package collection',
  批量集包方式: 'Batch package mode',
  承运单号: 'Carrier bill number',
  投放: 'Release',
  投放对象: 'Target',
  投放数量: 'Quantity',
  抛货方式: 'Casting mode',
  抛货配置: 'Casting configuration',
  抢券时间: 'Coupon grabbing time',
  抬头类型: 'Header type',
  抵用券: 'Credit Coupon',
  抵用券优惠: 'Credit Coupon Offer',
  抵用券减免: 'Credit Coupon Reductions',
  抵用券金额: 'Coupon amount',
  拖拽行可以进行排序: 'Drag and drop rows can be sorted',
  拣货时间: 'Picking time',
  拼团名称: 'Grouping name',
  拼团子订单详细: 'Grouping sub order details',
  拼团已完成: 'Grouping completed',
  拼团背景图片: 'Grouping background image',
  拼团订单号: 'Grouping order number',
  拼团路线: 'Tour route',
  拼团进行中: 'The group is in progress',
  按区域编号自动排序: 'Automatic sorting by area code',
  按单位计费重量收费: 'Charge by unit billing weight',
  按固定数值金额: 'By fixed value amount',
  按固定金额: 'By fixed amount',
  按固定金额提成: 'By fixed amount of commission',
  按地区分类显示: 'Display by region',
  按最小: 'By minimum',
  按比例提成: 'By percentage commission',
  按比例计佣时仅计算实际运费佣金不包含增值费用保险费用抵用券等:
    'For pro-rata commission, only the actual freight commission is calculated（Excluding value-added fees, insurance fees, coupons, etc.）',
  按箱收费: 'Charge by the case',
  按计算的运费比例: 'By calculated freight rate',
  按计费重量计佣设置每单位重量佣金: 'Commission by billing weight（set commission per unit of weight）',
  按订单收费: 'Charge by order',
  按订单金额比例: 'Proportional to order amount',
  按路线: 'By route',
  按预报单号: 'By forecast order number',
  按预报批次集包: 'Collect packages by forecast batch',
  授权公开拼团团长: ' Authorize open group leader',
  授权时间: 'Authorization time',
  排序: 'Sort by',
  推荐: 'Recommend',
  推荐将小程序码放在公众号或广告插图进行推广: 'Recommend to put the small program code in the public or advertising illustration for promotion',
  推荐货位: 'Recommended space',
  描述: 'Description',
  提交: 'Submit',
  提交体积重量: 'Submit Volume Weight',
  提交包裹: 'Submit Package',
  提交开始日期: 'Submit Start Date',
  提交拼团: 'Submit Grouping',
  提交时间: 'Submit Time',
  提交结束日期: 'Submit End Date',
  提交结算: 'Submit Checkout',
  提交重量: 'Submit Weight',
  提现: 'Withdrawal',
  提现中: 'Withdrawal in progress',
  提现信息: 'Withdrawal Information',
  提现失败: 'Withdrawal failed',
  提现成功: 'Withdrawal successful',
  提现方式: 'Withdrawal method',
  提现明细: 'Withdrawal details',
  提现明细数: 'Withdrawal details Number',
  提现申请: 'Withdrawal request',
  提现申请中: 'Withdrawal application in progress',
  提现说明: 'Withdrawal instructions',
  提现说明内容: 'Withdrawal instructions',
  提现金额: 'Cash withdrawal amount',
  提示: 'Tips',
  提示仅阶梯计价模式路线可开启拼团: 'Tips：only“Tiered Pattern routes can be opened for grouping',
  提示信息: 'Tip Message',
  提示内容: 'Tip content',
  提示系统仅支持三级区域对上一级地址操作启用关闭或删除时对下级所有区域生效:
    'Tips：The system only supports three levels of areas, and when the upper level address operation is enabled/disabled, or deleted, it takes effect for all areas at the lower level',
  提货方式: 'Pickup Method',
  插入: 'Insert',
  搜索: 'Search',
  操作: 'Operation',
  操作人: 'Operators',
  操作仓库: 'Operation Warehouse',
  操作失败: 'Operation failed',
  操作成功: 'Operation success',
  操作手册: 'Operation manual',
  操作手册下载: 'Operation manual download',
  操作日志: 'Operation Log',
  操作时间: 'Operation Time',
  操作流程: 'Operation flow',
  操作货位: 'Operation position',
  支付信息: 'Payment Information',
  支付审核: 'Payment audit',
  支付成功送券: 'Payment success coupon delivery',
  支付方式: 'Payment method',
  支付时间: 'Payment time',
  支付状态: 'Payment status',
  支付类型: 'Payment Type',
  支付详情: 'Payment details',
  支付配置: 'Payment configuration',
  支付金额: 'Payment amount',
  支出: 'Expense',
  支出时间: 'Spending time',
  支持与帮助中心: 'Support & Help Center',
  支持仓库: 'Support Warehouse',
  支持国家: 'Support Country',
  支持国家地区: 'Support Country Regions',
  支持属性: 'Support Properties',
  支持线路: 'Support Lines',
  支持货到付款: 'Support Cash on Delivery',
  收件人: 'Recipient',
  收件人姓名: 'Recipient Name',
  收件人邮箱: 'Recipient Email',
  收件地址: 'Recipient Address',
  收件地址列表: 'Recipient Address List',
  收件电话: 'Recipient Phone',
  收入: 'Income',
  收到消息回复: 'Receive message reply',
  收取方式: 'Receipt Method',
  收支类型: 'Receipt type',
  收支规则: 'Rules of Receipt and Disbursement',
  收货: 'Receipt of goods',
  收货人: 'Consignee',
  收货人信息: 'Consignee Information',
  收货国家: 'Country of receipt',
  收货国家地区: 'Consignee country and region',
  收货形式: 'Consignee form',
  收货方式: 'Delivery method',
  收货自提点: 'Pick-up point',
  收费方式: 'Charging method',
  收费类型: 'Type of charge',
  收费范围: 'Charge range',
  改为已付款: 'Change to Paid',
  改为已签收: 'Change to signed for',
  改价: 'Change the price',
  改成货到付款: 'Change to cash on delivery',
  放券总数: 'Total number of coupons released',
  数字增值: 'Digital Value Added',
  数据: 'Data',
  数量: 'Quantity',
  整票固定费用: 'Whole ticket fixed fee',
  整票限重: 'Whole ticket weight limit',
  文件上传: 'File Upload',
  文字: 'Text',
  文章: 'Articles',
  文章分类: 'Article Categories',
  文章列表: 'Article List',
  文章类型: 'Article Type',
  文章链接: 'Article Links',
  新人通过老客户链接注册登录即可获券与新用户送券同时享受:
    'Newcomers can get coupons by registering and logging in through the old customer link（Enjoyed in conjunction with the new user free coupon）',
  新增包裹数: 'Number of new packages',
  新增国家地区: 'New countries and regions',
  新增增值费用: 'Add Value Added Fee',
  新增子栏目: 'New sub-section',
  新增客户下单排行榜: 'Add customer order ranking',
  新增客户数: 'Number of new customers',
  新增客户数个: 'Number of new customers',
  新增客户概览: 'New Customers Overview',
  新增客户预报量: 'New Customer Forecast',
  新增授权: 'New authorizations',
  新增订单数: 'Number of new orders',
  新增评价: 'Add new rating',
  新增评论: 'Add Comments',
  新增货位: 'Add space',
  新增费用: 'Add cost',
  新增链接: 'Add link',
  新密码: 'New password',
  新建收货地址: 'New shipping address',
  新用户支付一笔订单: 'New user pays one order',
  新用户福利券: 'New user benefit coupon',
  新线路名称: '*New line name',
  新闻: 'News',
  无: 'No',
  无上限: 'No limit',
  无人认领: 'Unclaimed',
  无人认领专区: 'Unclaimed area',
  日志: 'Journal',
  时: 'time',
  时间: 'Time',
  明细: 'Details',
  是: 'Yes',
  是否使用积分: 'Whether to use points',
  是否启用: 'Enabled or not',
  是否开启风险提示: 'Whether to turn on the risk alert',
  是否强制购买: 'Whether to force purchase',
  是否拼团线路: 'Whether to group routes',
  是否推荐: 'Whether to recommend',
  是否显示: 'Show or not',
  是否生效: 'Effective or not',
  是否确认删除: 'Whether to confirm the deletion',
  是否确认唤醒客户: 'Whether to confirm the wake up customers？',
  是否确认导出: 'Whether to confirm export？',
  是否确认批量唤醒客户: 'Whether to confirm the batch wake up customers？',
  是否确认更新代理二维码: 'Confirmation of updating agent QR code',
  是否确认退出登录: 'Confirmation of logging out？',
  是否结算: 'Whether to settle',
  是否自提线路: 'Whether to pick up the line',
  是否默认: 'Default',
  显示时间: 'Show time',
  普通抵用券: 'General credit coupon',
  普通纸质发票: 'Ordinary paper invoice',
  暂不开启短信通知: 'Temporarily not open SMS notification',
  暂无数据: 'No data',
  暂无物流消息: 'No logistics news',
  暂无符合条件的路线: 'No eligible route',
  更换收货人信息: 'Change consignee information',
  更改: 'Change',
  更改仓库: 'Change of warehouse',
  更改地址: 'Change address',
  更改状态: 'Change Status',
  更改线路: 'Change Route',
  更新二程单号: 'Update 2 way bill number',
  更新代理二维码: 'Update Agent QR Code',
  更新多箱物流: 'Update multi-case logistics',
  更新物流: 'Update logistics',
  更新物流单号二程: 'Update logistics single number two course',
  更新物流状态: 'Update logistics status',
  更新物流轨迹: 'Update logistics track',
  最低收费: 'Minimum charge',
  最低消费: 'Minimum consumption',
  最低消费金额: 'Minimum consumption amount',
  最后下单时间: 'Last order time',
  最后操作时间: 'Last operation time',
  最后登录日期: 'Last login date',
  最后登录时间: 'Last login time',
  最大重量: 'Max. weight',
  最小重量: 'Min Weight',
  最终价格: '*Final Price',
  最近唤醒时间: 'Last wake up time',
  最高收费: 'Maximum charge',
  最高收费为: 'Maximum charge for',
  有效时长: 'Valid time',
  有效期: 'Valid period',
  服务: 'Service',
  服务名称: 'Service Name',
  服务器域名: 'Server Domain',
  服务器配置: 'Server Configuration',
  服务配置: 'Service Configuration',
  未下单天: 'Unordered days',
  未下单天数大于: 'Number of days without order is greater than',
  未使用数量: 'Unused quantity',
  未入库: 'Uninvited',
  未入库丢包预警: 'Uninventoried packet loss warning',
  未到自提点: 'No pickup point',
  未发货: 'Not shipped',
  未启用: '（Not activated）',
  未处理: 'Not processed',
  未开始: 'Not started',
  未打包: 'Not Packed',
  未提交: 'Not Submitted',
  未支付: 'Not paid',
  未生效: 'Not effective',
  未登录天: 'Not logged（days）',
  未登录天数大于: 'Unregistered days greater than',
  未结算: 'unsettled',
  未结算总金额: 'Total unsettled amount',
  未达门槛重量计费系数: 'Unreached threshold weight billing factor',
  本月新增客户: 'New customers this month',
  本月新增订单: 'New orders this month',
  本月预报包裹: "This month's forecast parcels",
  本次同时预报了: 'This time also forecasted',
  材质: 'Material',
  条件: 'Condition',
  查看分区表: 'View Partition Table',
  查看支付详情: 'View payment details',
  查看自提点支持线路: 'View pickup point support lines',
  查询: 'Search',
  查询结果: 'Query Results',
  标准模式: 'Standard Template',
  标准模版下载: 'Standard Template Download',
  标签: '*Tags',
  标题: 'Title',
  标题列表: 'Title List',
  栏目: 'Column',
  栏目名称: 'Column name',
  栏目图片: 'Column picture',
  栏目类型: 'Column type',
  栏目链接: 'Column Link',
  根据列表筛选条件: '(Filter conditions according to the list)',
  根据模版内容填充物流信息: 'Fill the material flow information according to the template content',
  根据阶梯拆分总体积每一部分按对应价格计算相加为总价:
    'According to the total volume of the ladder split each part is calculated according to the corresponding price and added up to the total price',
  模板类型: 'Template Type',
  模版上传: 'Template Upload',
  模版下载: 'Template Download',
  模版不能为空: 'Template cannot be empty',
  模版名称: 'Template name',
  模版标示: 'Template label',
  模版示例: 'Template example',
  模版类型: 'Template type',
  模版类型1: 'Template type 1',
  横幅: 'Banner',
  欢迎使用: 'Welcome',
  正常: 'Normal',
  正常件: 'Normal piece',
  此线路门槛重量: 'This line threshold weight',
  此视频暂无法播放请稍后再试: 'This video cannot be played at the moment please try again later',
  每个分区仅按最高项规则收取: 'Each division is charged only for the highest item rule',
  每级主菜单最多可以有五个子菜单栏目: 'Each level of the main menu can have up to five sub-menu columns',
  比例: 'Proportion',
  比例金额: 'Proportional Amount',
  比较符: 'Comparator',
  汇率配置: 'Exchange rate configuration',
  沉睡设置: 'Slumber Settings',
  注: 'Note',
  注册: 'Registration',
  注册个数: 'Number of registrations',
  注册日期: 'Registration date',
  注册时间: 'Registration time',
  注册用户: 'Registered Users',
  注册统计: 'Registration statistics',
  注册账户: 'Registered Accounts',
  注意修改计费重量后对应的价格表要重新设置: 'Attention：The corresponding price list has to be reset after changing the billing weight',
  注灰色部分向上取整: 'Note：Gray parts are rounded up',
  活动图: 'Event Map',
  流水号: 'Streaming number',
  测试: 'Test',
  海鸥集运管理系统: 'Hai-O Containerization Management System',
  海鸥集运:'Hai-O Collective shipping',
  消息模板: 'Message Template',
  消息类型: 'Message Type',
  消费: 'Consumption',
  添加: 'Add',
  添加价格表: 'Add Price List',
  添加会员等级: 'Add membership level',
  添加包裹: 'Add Package',
  添加包裹增值服务: 'Add parcel value-added services',
  添加员工组: 'Add Staff Group',
  添加商品分类: 'Add product categories',
  添加商品清单: 'Add product list',
  添加国家: 'Add Country',
  添加子菜单: 'Add submenu',
  添加客户: 'Add customer',
  添加客户组: 'Add customer group',
  添加属性: 'Add Properties',
  添加广告图: 'Add ad image',
  添加支付类型: 'Add Payment Type',
  添加新规则: 'Add new rules',
  添加明细: 'Add details',
  添加标签: 'Add Tags',
  添加渠道: 'Add channel',
  添加物流信息: 'Add logistics information',
  添加等级: 'Add level',
  添加菜单: 'Add menu',
  添加行: 'Add line',
  添加订单增值服务: 'Add order value-added services',
  添加语言: 'Add language',
  添加通知信息后客户在下单选择该地区的地址时会弹出对应提示:
    '添After adding the notification message, the corresponding prompt will pop up when the customer places an order and selects the address of the region',
  添加邮件模版: 'Add Email Template',
  清关备注: 'Customs clearance notes',
  清关编码: 'Customs Clearance Code',
  清除: 'Clearance',
  渠道中文名: 'Channel Chinese Name',
  渠道代码: 'Channel Code',
  渠道单价: 'Channel unit price',
  渠道占比: 'Channel share',
  渠道号: 'Channel Number',
  渠道名称: 'Channel Name',
  渠道增值服务: 'Channel Value-added Service',
  渠道属性: '*Channel Properties',
  渠道数量: 'Number of Channels',
  渠道最小: 'Channel Min',
  渠道服务费: 'Channel Service Fee',
  渠道标签: 'Channel Label',
  渠道标签在客户端仅作展示无特定功能: 'The channel tag is only for display in the client, no specific function',
  渠道规则: 'Channel Rules',
  渠道规则费: 'Channel rules fee',
  渠道说明: 'Channel description',
  渠道限制规则: 'Channel Restriction Rules',
  渠道限制费: 'Channel Restriction Fee',
  温馨提示: 'Warm Tips',
  温馨提示主要提醒客户需要注意的事项在客户端仓库地址页面显示:
    'Warm Tips（The main reminder of what the client needs to pay attention to is displayed on the client repository address page）',
  满足以下条件之一: 'Meet one of the following conditions',
  点击上传: 'Click to upload',
  点击以下按钮返回主页: 'Click the following button to return to the home page',
  点击修改: 'Click to modify',
  照片: 'Photo',
  物品: 'Item',
  物品价值: 'Item Value',
  物品价值区间: 'Value range',
  物品分类: 'Item classification',
  物品单价: 'Item unit price',
  物品名称: 'Item name',
  物品属性: 'Property',
  物品属性选择方式: 'Attribute selection method',
  物品总价值: 'Total Value',
  物品照片: 'Item photo',
  物品重量: 'Item weight',
  物流信息: 'Logistics information',
  物流单号: 'Logistics bill number',
  物流查询页图: 'Logistics Inquiry Page Map',
  物流状态: 'Logistics Status',
  物流评分: 'Logistics score',
  物流轨迹: 'Logistics track',
  特定会员等级: 'Specific Member Level',
  特定用户: 'Specific Users',
  特定用户组: 'Specific user group',
  状态: 'Status',
  生效: 'Effective',
  生效中: 'In effect',
  生效时间: 'Effective time',
  生效状态: 'Effective Status',
  用户名: 'User Name',
  用户抢券: 'User Coupon',
  用户注册即送券: 'User registration coupon',
  用户注册登陆: 'User Registration Login',
  申报价值: 'Declare value',
  申报价值比例: 'Declared Value Ratio',
  申报总值: 'Total declared value',
  申请增值服务: 'Application for value-added services',
  申请打包包裹记录: 'Application for packing parcel record',
  申请打包合箱: 'Application for packing combined box',
  申请打包备注: 'Application for packing remarks',
  申请时间: 'Application time',
  申请通过: 'Application passed',
  申请集包时如超过限制条件则无法选择该自提点不填写则不启用:
    'If you exceed the restrictions when applying for a collection package, you will not be able to select this pickup point. If you do not fill in, it will not be enabled',
  电子邮箱: 'Email',
  电话: 'Phone number',
  留仓物品: 'Items left in storage',
  登录: 'Login',
  登录信息: 'Login Information',
  登录开始日期: 'Login Start Date',
  登录时间: 'Login Time',
  登录结束日期: 'Login End Date',
  登录页背景图: 'Login page background image',
  的商品清单: 'List of products',
  的物流轨迹: 'Logistics track',
  目的国家: 'Destination country',
  目的地: 'Destination',
  直接出库: 'Directly out of the warehouse',
  相关订单: 'Related orders',
  省: 'Province',
  真实姓名: 'Real Name',
  短信模版: 'SMS template',
  短信模版系统内: 'SMS template (in the system)',
  短信类型: 'SMS Type',
  短信配置聚合: 'SMS Configuration——Polymerization',
  破损: 'Broken',
  确定: 'Determine',
  确定要作废优惠券吗: 'Are you sure you want to void the coupon?',
  确定要删除优惠券吗: 'Are you sure you want to delete the coupon?',
  确定要重新生成会员编号吗原来的编号将会被重置可能会部分影响到包裹订单出入库:
    'Sure you want to regenerate your membership number? The original number will be reset, which may partially affect the parcel orders in and out of the warehouse',
  确认信息: 'Confirmation Information',
  确认密码: 'Confirm Password',
  确认支付信息: 'Confirm payment information',
  确认新密码: 'Confirm new password',
  确认金额: 'Confirm amount',
  神说这个页面不存在: 'God says this page does not exist',
  禁止登录: 'Disable login',
  禁用: 'Forbidden to use',
  私人: 'Private',
  种类: 'Category',
  秒: 'seconds',
  积分: 'Points',
  积分抵扣: 'Points credit',
  积分抵扣的金额: 'The amount of points credit',
  积分抵扣金额: 'Point credit amount',
  称重开始日期: 'Weighing start date',
  称重时间: 'Weighing Time',
  称重结束日期: 'Weighing End Date',
  称重重量: 'Weighing Weight',
  移除: 'Remove',
  移除发货单: 'Remove Shipping Order',
  移除拼团: 'Remove Grouping',
  移除该团员后团员已提交的拼团包裹将会退回原仓库您确定要移除该团员吗:
    "After removing the group member, the group member's submitted packages will be returned to the original warehouse, are you sure you want to remove the group member?",
  税号: 'Tax code',
  税款: 'Taxes（¥）',
  税率: 'Tax rate（%）',
  立即查询: 'Inquire Now',
  立方: '(Cube)',
  立方米: 'cubic meters',
  第三方审核状态: 'Third party audit status',
  第三方物流查询服务: 'Third party logistics inquiry service',
  第三方登录: 'Third Party Login',
  第三方短信服务: 'Third party SMS service',
  等于: 'Equivalent to',
  等级名称: 'Grade Name',
  等级成长值: 'Grade Growth Value',
  签收: 'Sign-in',
  签收日志: 'Signing Log',
  签收时间: 'Signing time',
  签收照片: 'Receipt photo:',
  简体中文: 'Simplified Chinese',
  管理: 'Management',
  管理系统: 'Management System',
  管理自定义物流轨迹: 'Manage custom logistics track',
  箱: 'Boxes',
  箱号: 'Box number',
  箱总数: 'Total number of boxes',
  箱数: 'Number of boxes',
  类型: 'Type',
  类型单位实际重量固定费用收取方式强制收取: 'Type: Fixed fee per unit of actual weight Collection method: Mandatory',
  类型单位实际重量固定费用收取方式自愿勾选: 'Type: Fixed fee per unit of actual weight Collection method: Voluntary check box',
  类型单位计费重量固定费用收取方式强制收取: 'Type: unit billing weight fixed fee Collection method: mandatory collection',
  类型单位计费重量固定费用收取方式自愿勾选: 'Type: unit billing weight fixed fee Collection method: voluntary check box',
  类型单箱固定费用收取方式强制收取: 'Type: single box fixed fee Collection method: mandatory',
  类型单箱固定费用收取方式自愿勾选: 'Type: single box fixed fee Collection method: voluntary checkbox',
  类型整票固定费用收取方式强制收取: 'Type: Whole ticket fixed fee Collection method: Mandatory',
  类型整票固定费用收取方式自愿勾选: 'Type: Whole ticket fixed fee Collection method: Voluntary checkbox',
  类型申报价值比例收取方式强制收取: 'Type: declared value percentage Collection method: mandatory',
  类型申报价值比例收取方式自愿勾选: 'Type: declared value ratio Collection method: voluntary checkbox',
  类型运费比例收取方式强制收取: 'Type: Freight rate Collection method: Mandatory collection',
  类型运费比例收取方式自愿勾选: 'Type: Freight rate Collection method: Voluntary checkbox',
  精选: 'Featured',
  系统内服务短信: 'In-System Service SMS',
  系统内物流查询服务: 'In-system logistics inquiry service',
  系统开放线路: 'System Open Line',
  系统有效期: 'System Expiry Date',
  系统服务配置: 'System Service Configuration',
  系统物流类型: 'System logistics type',
  系统通知: 'System notification',
  系统配置助手: 'System Configuration Assistant',
  纬度: 'Latitude',
  线路下单类型: 'Line order type',
  线路名称: 'Line name',
  线路类型: 'Line Type',
  线路统计: 'Line Statistics',
  线路送货方式: 'Line Delivery Method',
  经度: 'Longitude',
  结束日期: 'End Date',
  结算: 'Settlement',
  结算方式: 'Settlement Method',
  结算状态: 'Settlement Status',
  结算货币: 'Settlement Currency:',
  统一备注: 'Uniform Remarks',
  统计日期: 'Statistical date',
  续单价: 'Renewal Unit Price',
  续费: 'Renewal Fee',
  续费成本价: 'Renewal cost price',
  续重: 'Renewal weight',
  综合评分: 'Overall Rating',
  编辑会员等级: 'Edit Member Level',
  编辑位置: 'Edit Location',
  编辑发货单: 'Edit Shipping Orders',
  编辑图片: 'Edit Image',
  编辑增值费用: 'Edit Value Added Charges',
  编辑收货人: 'Edit Consignee',
  编辑收货人信息: 'Edit consignee information',
  编辑路线: 'Edit Route',
  编辑链接: 'Edit Link',
  编辑颜色: 'Edit Colors',
  网站: 'Website',
  网站名称: '*Website name',
  网站链接: 'Website Link',
  美中国际定制: 'US-China International Custom',
  考虑体积重: 'Consider volume weight',
  联系人: 'Contact person',
  联系方式: 'Contact information',
  联系电话: 'Contact number',
  背景图像: 'Background image',
  自动获取: 'Automatic acquisition',
  自动货位: 'Automatic position',
  自动货位功能: 'Auto-position function',
  自定义标签: 'Customized label',
  自定义物流类型: 'Customized logistics type',
  自定义轨迹类型: 'Custom track type',
  自定义配置: 'Custom configuration',
  自愿勾选: 'Voluntary ticking',
  自提: 'Self-pickup',
  自提点信息: 'Self-pickup point information',
  自提点公告设置: 'Pick-up point announcement settings',
  自提点名称: 'Pickup Point Name',
  自提点地址: 'Pickup Point Address',
  自提点提货: 'Pickup point pickup',
  自提点权限: 'Pickup Point Authority',
  自提点编号: 'Pickup Point Number',
  自提点规则: 'Self-pickup point rules',
  自提签收: 'Self-pickup sign-off',
  至: 'to',
  获券条件: 'Conditions for receiving vouchers',
  获取验证码: 'Get verification code',
  菜单名称: 'Menu Name',
  菜单类型: 'Menu Type',
  营业时间: 'Business Hours',
  营业额: 'Turnover',
  落地配配置: 'Landing with configuration',
  行业资讯: 'Industry Information',
  行为: 'Behavior',
  街道: 'Street',
  街道门牌号: 'Street door number',
  被关注回复: 'Followed reply',
  被关注回复最多只能同时发两条消息: 'Followed replies can only send a maximum of two messages at the same time',
  要求购买保险: 'Requirement to purchase insurance',
  覆盖: 'Coverage',
  覆盖模版: 'Coverage Template',
  规则名称: 'Rule Name',
  规则说明: 'Rule Description',
  规格: 'Specification',
  视频区: 'Video Zone',
  解锁: 'Unlock',
  计价方式: 'Counting mode',
  计价模式: 'Pricing mode',
  计佣方式: 'Commissioning method',
  计佣金额: 'Commission amount',
  计算: 'Calculation',
  计算方式: 'Calculation method',
  计算方式以分区一为例: 'Calculation method (using partition one as an example)',
  计算方式重量处于哪一个区间即采用该区间对应的基价单价计算费用:
    'Calculation method: The weight is in which interval, that is, the use of the interval corresponding to the "base price" "unit price" to calculate the cost：',
  计算方式重量处于哪一个区间即采用该区间对应的首费续单价计算费用:
    'Calculation method: The weight is in which range, that is, the corresponding "first fee" "renewal unit price" to calculate the cost of that range：',
  计费为首费: 'Billing is first charge',
  计费价格模式: '*Billing price model',
  计费价格模式说明: 'Description of the billing price model',
  计费体积: 'Billing volume',
  计费模式: 'Billing Model',
  计费维度: 'Billing Dimension',
  计费设置: 'Billing Settings',
  计费设置页面配置计费类型与首重续重重量阶梯等基础数据:
    'Configuration of billing type and basic data such as first weight, renewal weight, weight ladder, etc. on the "Billing Settings" page',
  计费重: '（Billing weight）',
  计费重量: 'Billing weight',
  计重模式: 'Weighting mode',
  订单发货: 'Order Shipping',
  订单号: 'Order Number',
  订单增值服务: 'Order Value Added Service',
  订单多箱打包: 'Orders packed in multiple boxes',
  订单多箱打包时每个打包箱重量分别上浮而不是整个上浮:
    'When orders are packed in multiple boxes, the weight of each packed box is floated up separately instead of the whole.',
  订单多箱打包重量向上取值: 'Order multi-case packing weight upward value',
  订单对比: 'Order Comparison',
  订单待支付通知: 'Order Pending Payment Notification',
  订单总数: 'Total Orders',
  订单打包: 'Order Packing',
  订单支付: 'Order Payment',
  订单数: 'Number of orders',
  订单日志: 'Order Log',
  订单概览: 'Order Overview',
  订单状态: 'Order Status',
  订单统计: 'Order Statistics',
  订单编号: 'Order Number',
  订单编码: 'Order Code',
  订单详情: 'Order details',
  订单金额: 'Order amount',
  认领: 'Claim',
  认领记录: 'Claim Record',
  记录: 'Record',
  设为推荐: 'Set as recommendation',
  设为推荐后该路线标为推荐路线: 'When set as recommended, the route is marked as recommended.',
  设为精选: 'Set as Featured',
  设为默认: 'Set as default',
  设置佣金: 'Set commission',
  设置门槛重量: 'Set threshold weight',
  设置面板: 'Set panel',
  评价: 'Evaluation:',
  评价内容: 'Evaluation content',
  评分: 'Rate',
  评论区: 'Comment Zone',
  该区间续单价: 'The interval continues the unit price',
  该操作无法恢复请确认该路线彻底弃用后再删除: 'This operation cannot be recovered, so please make sure the route is completely abandoned before deleting it.',
  该数据统计包含已删除活动数据已发放券正常使用可前往抵用券管理查看:
    'The statistics include deleted activity data, issued coupons are normally used, you can go to the coupon management to view',
  该申请还未开票: 'The application has not yet been invoiced',
  该订单为待审核状态无法更改付款状态请操作审核: 'The order is pending audit status, can not change the payment status, please operate audit',
  该记录还未审核: 'This record has not been reviewed',
  该重量仅用于判断本团购单的价格档位: 'This weight is only used to determine the price bracket of this group purchase order',
  详细: 'Details',
  详细地址: 'Detailed address',
  详细清单: 'Detailed list',
  语言: 'Language',
  语言编码: 'Language code',
  说明: 'Description',
  请上传图片类型文件: 'Please upload image type files',
  请上传格式正确的文件: 'Please upload a file with the correct format',
  请上传背景图像: 'Please upload a background image',
  请先输入手机号: 'Please enter your cell phone number first',
  请先选择所属国家地区: 'Please select your country first',
  请再次输入密码: 'Please enter your password again',
  请再次输入新密码: 'Please enter a new password again',
  请根据需求选择模板并下载: 'Please select a template according to your needs and download it',
  请检查您输入的网址是否正确: 'Please check if the URL you entered is correct',
  请求号码: 'Request Number',
  请求客户: 'Requesting Customer',
  请求类型: 'Request Type',
  请注意以下内容请输入对应的: 'Please note that the following content please enter the corresponding',
  请确认您的密码: 'Please confirm your password',
  请输入: 'Please enter',
  请输入11位手机号码: 'Please enter 11-digit cell phone number',
  请输入820位密码区分大小写: 'Please enter the 820-digit case-sensitive password',
  请输入一级分类名称: 'Please enter a category name',
  请输入下单支付最小满足金额: 'Please enter the minimum amount to be paid for the order',
  请输入仓库名称: 'Please enter the name of the warehouse',
  请输入代理名称: 'Please enter the name of the agent',
  请输入代理用户: 'lease enter the agent user',
  请输入件数: 'Please enter the number of pieces',
  请输入价格表名称: 'Please enter the name of the price list',
  请输入体积系数: 'Please enter the volume factor',
  请输入佣金分成: 'Please enter the commission share',
  请输入值空值为不限制: 'Please enter the value (empty value is unrestricted)',
  请输入关键字: 'Please enter keywords',
  请输入券最大上限金额: 'Please enter the maximum voucher amount',
  请输入包裹编码: 'Please enter the parcel code',
  请输入区块详情: 'Please enter the block details',
  请输入单人限领数量: 'Please enter the single person limit number',
  请输入单号: 'Please enter the order number',
  请输入原密码: 'Please enter the original password',
  请输入发件人名称: "Please enter the sender's name",
  请输入发件人密码: "Please enter the sender's password",
  请输入发件人用户名: "Please enter the sender's user name",
  请输入发件人邮件: "Please enter the sender's email",
  请输入名称: 'Please enter a name',
  请输入员工组: 'Please enter employee group',
  请输入品牌: 'Please enter brand',
  请输入固定值或百分比: 'Please enter a fixed value or percentage %',
  请输入地址: 'Please enter an address',
  请输入城市: 'Please enter a city',
  请输入备注: 'Please enter a note',
  请输入失效时间: 'Please enter expiration date',
  请输入姓名: 'Please enter your name',
  请输入存放货位: 'Please enter the storage space',
  请输入实际重量: 'Please enter actual weight',
  请输入客户: 'Please enter customer',
  请输入密码: 'Please enter your password',
  请输入异常件备注不能超过250个字: 'Please enter a note about the exceptions, no more than 250 characters',
  请输入微信号: 'Please enter the micro signal',
  请输入微信昵称: 'Please enter your WeChat nickname',
  请输入快递单号: 'Please enter the courier number',
  请输入快递单号搜索多个单号请用回车区分: 'Please enter the express single number search, multiple single number, please use the carriage return to distinguish',
  请输入您的手机号: 'Please enter your cell phone number',
  请输入手机号: 'Please enter your cell phone number',
  请输入扣款金额: 'Please enter the amount to be deducted',
  请输入排序: 'Please enter the sort',
  请输入收件人: 'Please enter the recipient',
  请输入收件人姓名: "Please enter the recipient's name",
  请输入收件电话: "Please enter the recipient's phone number",
  请输入放券总数: 'Please enter the total number of coupons released',
  请输入新密码: 'Please enter a new password',
  请输入新线路名称: 'Please enter the new line name',
  请输入旧密码: 'Please enter the old password',
  请输入最低收费空值为不设限制: 'Please enter the minimum charge (empty value for no limit)',
  请输入最低消费: 'Please enter minimum consumption',
  请输入最大重量: 'Please enter the maximum weight',
  请输入最小重量: 'Please enter minimum weight',
  请输入最高收费空值为不设限制: 'Please enter the maximum charge (empty value for no limit)',
  请输入有效时长: 'Please enter a valid duration',
  请输入有效期: 'Please enter the expiration date',
  请输入有效期例如78而不是20200101: 'Please enter the expiration date, e.g. 78 instead of 2020-01-01',
  请输入标签: 'Please enter a tag',
  请输入标题: 'Please enter a title',
  请输入栏目名称: 'Please enter the column name',
  请输入模版名称: '*Please enter the name of the template',
  请输入模版标示: 'Please enter the template label',
  请输入正确天数: 'Please enter the correct number of days',
  请输入正确的手机号: 'Please enter the correct cell phone number',
  请输入正确的邮箱地址: 'Please enter the correct email address',
  请输入汇率: 'Please enter the exchange rate',
  请输入清关备注: 'Please enter the customs clearance notes',
  请输入渠道单价: 'Please enter the channel unit price',
  请输入渠道名称: 'Please enter the channel name',
  请输入温馨提示: 'Please enter a warm reminder',
  请输入物品名称: 'Please enter the item nam',
  请输入物品总价值: 'Please enter the total value of the item',
  请输入生效时间: 'Please enter the effective date',
  请输入用户名: 'Please enter your username',
  请输入电话: 'Please enter your phone number',
  请输入电话号码: 'Please enter your phone number',
  请输入留仓物品: 'Please enter the items left in storage',
  请输入线路名称: 'Please enter the line name',
  请输入结束价格: 'Please enter the ending price',
  请输入续费: 'Please enter the renewal fee',
  请输入续重: 'Please enter refill weight',
  请输入网站名称: 'Please enter the name of the site',
  请输入联系人: 'Please enter a contact person',
  请输入联系电话: 'Please enter your contact phone number',
  请输入自提点名称: 'Please enter the name of the pick-up point',
  请输入自提点编号: 'Please enter the pick-up point number',
  请输入街道: 'Please enter the street',
  请输入规则名称: 'Please enter the name of the rule',
  请输入订单号搜索多个单号请用回车区分: 'Please enter the order number to search, multiple order numbers please use the carriage return to distinguish',
  请输入详细地址: 'Please enter full address',
  请输入货位: 'Please enter the space',
  请输入费用说明: 'Please enter the cost description',
  请输入起始价格: 'Please enter the starting price',
  请输入转运快递单号: 'Please enter the forwarding courier number',
  请输入邮箱: 'Please enter your email',
  请输入邮箱地址: 'Please enter your email address',
  请输入邮箱或手机号: 'Please enter your email address or cell phone number',
  请输入邮编: 'Please enter your zip code',
  请输入重量: 'Please enter weight',
  请输入金额: 'Please enter the amount',
  请输入门牌号: 'Please enter the door number',
  请输入附加地址: 'Please enter additional address',
  请输入限制数值: 'Please enter a limit value',
  请输入预设充值金额: 'Please enter the preset recharge amount',
  请输入首费: 'Please enter the first fee',
  请输入首重: 'Please enter the first weight',
  请输入验证码: 'Please enter the verification code',
  请选择: 'Please select',
  请选择仓库: 'Please select the warehouse',
  请选择使用范围: 'Please select the range of use',
  请选择分区: 'Please select partition',
  请选择分类: 'Please select a category',
  请选择包裹: 'Please select parcel',
  请选择区号: 'Please select the area code',
  请选择单个订单进行操作: 'Please select a single order for operation',
  请选择同时满足以下规则为沉睡会员: 'Please choose to also meet the following rules for sleeping members：',
  请选择员工: 'Please select staff',
  请选择员工组: 'Please select employee group',
  请选择商品: 'Please select product',
  请选择国家: 'Please select country',
  请选择国家地区: 'Please select a country/region',
  请选择国家或地区: 'Please select a country or region',
  请选择客户: 'Please select a customer',
  请选择客户或客户组: 'Please select a customer or customer group',
  请选择客户组: 'Please select a customer group',
  请选择寄往仓库: 'Please select the warehouse to ship to',
  请选择所属国家地区: 'Please select your country',
  请选择支持仓库: 'Please select support warehouse',
  请选择支持国家或地区: 'Please select support country or region',
  请选择收支类型: 'Please select the type of payment and receipt',
  请选择收支规则: 'Please select the rules of payment and receipt',
  请选择文章类型: 'Please select article type',
  请选择模版类型: 'Please select the template type',
  请选择物品属性: 'Please select item properties',
  请选择状态: 'Please select the status',
  请选择线路类型: 'Please select the line type',
  请选择结算方式: 'Please select the settlement method',
  请选择结算状态: 'Please select the settlement status',
  请选择获券条件: 'Please select the conditions for receiving the voucher',
  请选择要上传的文件: 'Please select the file you want to upload',
  请选择路线: 'Please select the route',
  请选择预设模版: '*Please select a preset template',
  请选择默认自提点: 'Please select the default pick-up point',
  财务统计: 'Financial Statistics',
  账户名: 'Account Name',
  货位: 'Cargo space',
  货位数量: 'Number of spaces',
  货到付款: 'Cash on delivery',
  货区可多选当包裹为无人认领时强制放入专区不受其他规则限制:
    'Cargo area can be multi-selected, when the package is unclaimed, forced into the zone, not subject to other rules',
  货品名称: 'Name of goods',
  货币单位: 'Currency unit',
  货量统计: 'Quantity statistics',
  购买: 'Purchase',
  购买记录: 'Purchase record',
  费用: 'Cost',
  费用值: 'Cost Value',
  费用清单: 'List of fees',
  费用类型: 'Fee Type',
  费用详情: 'Fee Details',
  赠送金额: 'Complimentary amount',
  起始: 'Start',
  起始重量: 'Starting weight',
  超期收费: 'Overdue charge',
  跟踪: 'Tracking',
  跟踪进度: 'Tracking progress',
  路线筛选: 'Route Filtering',
  路线配置: 'Route Configuration',
  身份: 'Identity',
  身份证反面: 'ID Reverse',
  身份证号码: 'ID card number',
  身份证正面: 'ID card front',
  身份验证: 'Identity verification',
  轨迹: 'Track',
  轨迹数量: 'Number of tracks',
  转义符号: 'Transitive Symbols',
  转化率: 'Conversion Rate',
  转账支付: 'Transfer Payment',
  转账支付账户: 'Transfer Payment Account',
  转账账号: 'Transfer Account Number',
  转账金额: 'Transfer Amount',
  转运公司: 'Forwarding Company',
  转运单号: 'Transfer Order Number',
  转运快递公司: 'Transfer Courier Company',
  转运快递单号: 'Transfer Express Single Number',
  转运快递单号头程: 'Forwarding express single number - Headway',
  转运规则: 'Forwarding rules',
  转运订单号: 'Forwarding order number',
  轮播图: 'Rotation map',
  软件下载: 'Software Download',
  达成免抛条件时: 'When reaching the no-drop condition',
  过期数量: 'Expired Quantity',
  运单详情: 'Shipping Order Details',
  运费: 'Shipping cost',
  运费价格比例仅运费: 'Shipping price ratio (shipping only)',
  运费比例: 'Shipping rate',
  运费试算: 'Trial calculation of shipping costs',
  运送时效: 'Shipping time',
  近7天: 'Nearly 7 days',
  近30天: 'Nearly 30 days',
  近一周: 'Nearly a week',
  近一月: 'Nearly one month',
  近半年: 'Nearly half a year',
  返回: 'Back',
  返回登录: 'Back to Login',
  返回首页: 'Back to top',
  还有团员未提交包裹提交包裹会自动踢出该团员您确定要提交该拼团吗:
    'There are still group members who have not submitted the package, submitting the package will automatically kick out the group member, are you sure you want to submit the grouping?',
  进行中: 'In progress',
  违禁品: 'Contraband',
  连接方式: 'Connection',
  追加: 'add-on',
  追加模版: 'Append Template',
  退出失败: 'Exit failed',
  退回余额: 'Refund balance',
  退回未入库: 'Refund unaccounted for',
  退款: 'Refund',
  退款信息: 'Refund Information',
  退款审核: 'Refund Review',
  退款方式: 'Refund Method',
  退款金额: 'Refund amount',
  送券条件: 'Delivery conditions',
  送货上门: 'Home Delivery',
  送货上门与自提: 'Home Delivery and Pickup',
  送货方式: '*Delivery Method',
  适用对象: 'Applicable to',
  适用渠道: 'Applicable channels',
  选择: 'Select',
  选择分类: 'Select category',
  选择包裹数与件数: 'Select number of packages and pieces',
  选择区域: 'Select region',
  选择员工: 'Select Staff',
  选择客户: 'Select Customer',
  选择开启会忽略当次地址精确度检查: 'Selecting On will ignore the current address accuracy check.',
  选择操作: 'Select Operation',
  选择日期: 'Select date',
  选择标题: 'Select title',
  选择模版: 'Select Template',
  选择自提点: 'Select pick-up point',
  选择语言: 'Select language',
  选择路线: 'Select route',
  选用预设分区表: 'Select preset partition table',
  选用预设分区表后将在当前渠道增加分区需设置价格表后再启用分区:
    '*After selecting the preset partition table, the partition will be added to the current channel, you need to set the price list and then enable the partition',
  邀请人: 'Invitees',
  邀请人数: 'Number of Invitees',
  邀请客户成交订单数: 'The number of orders closed by invited customers',
  邀请客户成交订单数个: 'Number of orders closed by invited customers(individual)',
  邀请客户成交金额: 'Invite customer transaction amount',
  邀请排行榜: 'Invitation Ranking',
  邀请新人达成要求后邀请人可获券: 'After inviting a new person to meet the requirements, the inviter will receive a voucher',
  邀请记录: 'Invitation Record',
  邮件内容: '*Email content',
  邮件标题: 'Email title',
  邮件模版: 'Email Template',
  邮件通知: 'Email notification',
  邮件配置: 'Email Configuration',
  邮箱: 'Mailbox',
  邮箱发件信息配置: 'Mailbox Outgoing Message Configuration',
  邮箱激活: 'Mailbox Activation',
  邮编: 'Zip Code',
  配置信息: 'Configuration Information',
  配置计佣模版: 'Configure Commissioning Template',
  重开发票: 'Re-invoicing',
  重新生成: 'Regenerate',
  重新申请: 'Reapply',
  重置: 'Reset',
  重置登录密码: 'Reset Login Password',
  重量: 'Weight',
  重量不能为空: 'Weight cannot be empty',
  重量体积重: 'Weight Volume Weight',
  重量单位: 'Unit of weight：',
  重量尺寸: 'Weight size',
  重量范围: 'Weight range',
  重量计费: 'Weight billing',
  金额: 'Amount',
  银行卡号: 'Bank Card Number',
  银行名称: 'Bank Name',
  银行账号: 'Bank Account Number',
  链接: 'Link',
  链接模块名称: 'Link Module Name',
  链接自定义图片只需要上传一张显示图片长宽比54: 'Link custom image only need to upload one, display image aspect ratio 5:4',
  销售价格: 'Selling Price',
  销售价格表: 'Selling Price List',
  锁定: 'Lock',
  长: 'Length',
  长宽高: 'Length Width Height',
  长度单位: 'Length unit：',
  长度在6到32个字符: 'Length in 6 to 32 characters',
  长度在8到20个字符: 'Length in 8 to 20 characters',
  门槛重量: 'Threshold weight',
  门牌号: 'Door number',
  问题件: 'Issue pieces',
  阶梯价格模式: 'Step price model',
  阶梯总价: 'Step total price',
  阶梯首重续重模式: 'Step first weight renewal weight mode',
  附件: 'Attachment',
  附加地址: 'Additional Addresses',
  附加费用: 'Additional Charges',
  限制出仓: 'Restricted Outbound',
  限制出仓提示: 'Restricted Outbound Tips',
  限定: 'Limitations',
  限定方式: 'Restriction Method',
  限定条件: 'Limit Conditions',
  限重: 'Weight Restriction',
  集运: 'Transport',
  集运系统仓库桌面软件: 'Collective transport system warehouse desktop software',
  非精选: 'Non-Selected',
  面单地址: 'Facsimile address',
  面单对接: 'Face Sheet Docking',
  项目名称: 'Project Name',
  预付: 'Prepayment',
  预报与入库: 'Prepayment & Inbound',
  预报仓库: 'Prepayment Warehouse',
  预报信息: 'Prepayment Information',
  预报单号: 'Prepayment Order Number',
  预报时间: 'Prepayment Time',
  预报申请服务: 'Forecast Application Service',
  预报量: 'Forecast volume',
  预览: 'Preview',
  预览打印标签: 'Preview Print Labels',
  预警: 'Early Warning',
  预计费用: 'Estimated Cost',
  预计重量: 'Estimated weight',
  预设充值金额: 'Preset recharge amount',
  预设分区表: 'Preset partition table',
  首次系统使用需要完成以下配置才能正常上线运营: 'The first time the system is used, the following configurations need to be completed for normal online operation',
  首费: 'First Fee',
  首费体积: '*Volume of down payment',
  首费成本价: 'First Charge Cost',
  首重: 'First weight',
  首重价格: '*First weight price',
  首重单位续重: 'First weight/unit renewal weight',
  首重续重模式: 'First weight renewal mode',
  验证码: 'Verification Code',
  验证身份: 'Verify identity',
  高: 'High',
  高和宽一致只需要填写一个参数: 'The height and width are the same, only one parameter needs to be filled',
  高级搜索: 'Advanced Search',
  高级设置: 'Advanced Settings',
  高级配置: 'Advanced Configuration',
  默认: 'Default',
  默认佣金: 'Default Commissions',
  默认支付模式: 'Default Payment Mode',
  默认收货信息: 'Default Receiving Information',
  默认自提点: 'Default Pickup Point',
  常规下单与拼团下单都可选: 'Both regular and group orders are available',
  常规下单不可选该路线仅拼团可选用: 'The route is not available for regular orders, only for group orders',
  订单分箱号: 'Order sub-case number',
  拼团订单编号: 'Group order number',
  发货单编号: 'Shipping order number',
  盘点单编号: 'Inventory order number',
  转为异常件: 'Turned into abnormal pieces',
  处理异常: 'Handling Exceptions',
  异常说明: 'Exception Description',
  批量提交: 'Batch Submission',
  报关信息: 'Customs Declaration Information',
  查看: 'View',
  重新提交: 'Resubmit',
  对接日志: 'Docking Log',
  示例: 'Example',
  默认仓库: 'Default repository',
  新用户注册: 'New user registration',
  新用户下单: 'New user order',
  成长值有效期: 'Growth value validity',
  规则限制: 'Rule Limit',
  邀新累计成长值: 'Invite new users to accumulate growth value',
  快速转运: 'Fast Transit',
  批量转运: 'Bulk Transfer',
  批量通知: 'Batch Notification',
  导出产能: 'Export capacity',
  用户组描述: 'User Group Description',
  请输入员工组中文名: 'Please enter the Chinese name of the staff group',
  请输入员工组英文名: 'Please enter the English name of the employee group',
  请输入用户组描述: 'Please enter a user group description',
  '步骤 1': 'Step 1',
  '步骤 2': 'Step 2',
  标签模板: 'Label Templates',
  客户模板: 'Customer Templates',
  批量分配客服: 'Batch Assignment Customer Service',
  批量分配销售: 'Bulk distribution sales',
  批量分配客户组: 'Batch assignment of customer groups',
  新增用户: 'Adding new users',
  用户手机号和邮箱需要是唯一: 'User cell phone number and email address need to be unique',
  用户手机号: 'User cell phone number',
  用户邮箱: 'User Email',
  用户密码: 'User Password',
  用户昵称: 'User nickname',
  请输入用户手机号: "Please enter the user's cell phone number",
  请输入用户邮箱: 'Please enter your email address',
  请输入用户密码: 'Please enter the user password',
  请输入用户昵称: 'Please enter a user nickname',
  VIP等级: 'VIP Level',
  请选择VIP等级: 'Please select VIP level',
  请选择所属客服: 'Please select the service you belong to',
  请选择所属销售: 'Please select the sales you belong to',
  请输入邀请人: 'Please enter the invitee',
  余额范围: 'Balance Range',
  请输入最小余额: 'Please enter the minimum balance',
  请输入最大余额: 'Please enter the maximum balance',
  积分范围: 'Point range',
  请输入最小积分: 'Please enter minimum points',
  请输入最大积分: 'Please enter the maximum number of points',
  订单数范围: 'Order Number Range',
  请输入最小订单数: 'Please enter the minimum order number',
  请输入最大订单数: 'Please enter the maximum number of orders',
  客户来源: 'Customer Sources',
  渠道来源: 'Channel Sources',
  客户ID: 'Customer ID',
  客户标签: 'Customer Tags',
  消费总额: 'Total consumption',
  客户分类: 'Customer Classification',
  '注: 每个客户仅能属于一个客户组': 'Note: Each client can only belong to one client group',
  同行货系统: 'Peer-to-peer system',
  解除授权: 'Deauthorization',
  同行货授权: 'Peer licensing',
  '注：每个客户可以属于多个标签组': 'Note: Each customer can belong to multiple tag groups',
  标签描述: 'Label Description',
  修改标签: 'Modify Tags',
  标签管理: 'Label Management',
  地址状态: 'Address Status',
  地址类型: 'Address Type',
  导出订单: 'Export orders',
  推广下单数: 'Promotion of the number of orders placed',
  推广成交数: 'Number of promotional deals',
  请输入客户组中文名: 'Please enter the Chinese name of the customer group',
  请输入客户组英文名: 'Please enter the English name of the customer group',
  请输入客户组描述: 'Please enter a customer group description',
  新增地址: 'Add address',
  批量导入地址: 'Batch import address',
  下载对应模版如实填写批量导入表后请以Excel形式保存点击第二步上传: 'Download the corresponding template, fill in the batch import form truthfully, please save it in Excel form, click the second step to upload',
  新增行: 'New line',
  标签名字: 'Label Name',
  引用次数: 'Number of citations',
  批量审核: 'Batch Review',
  模板名称: 'Template Name',
  请输入模板名称: 'Please enter the name of the template',
  '选择佣金层级后，请点击“生成佣金表”': 'After selecting the commission level, please click on "Generate Commission Table"',
  添加计佣模版: 'Add commission template',
  层级设置: 'Tier Setting',
  选择获取佣金层级: 'Choose to get a commission tier',
  一级: 'Level 1',
  二级: 'Level 2',
  三级: 'Level 3',
  生成佣金表: 'Generate commission table',
  佣金设置: 'Commission Setting',
  佣金试算: 'Commission Trial Calculation',
  客户消费渠道: 'Customer consumption channels',
  请选择渠道: 'Please select a channel',
  订单计佣金额: 'Order commission amount',
  输入试算金额: 'Enter trial amount',
  输入计费重量: 'Enter billing weight',
  计算佣金: 'Calculate commission',
  获得佣金: 'Get commission',
  一级佣金: 'Tier 1 Commission',
  会员ID: 'Member ID',
  '转化率(%)': 'Conversion rate (%)',
  批量预报: 'Batch Forecast',
  下载对应模版如实填写批量下单表后请以Excel形式保存点击第二步上传: "Download the corresponding template, fill in the batch order form truthfully, please save it in Excel form, click the second step to upload",
  批量包裹变更: 'Batch Parcel Change',
  批量修改: 'Batch Modification',
  批量导入发货单: 'Bulk import of shipping orders',
  第一步下载模板: 'Step 1: Download the template',
  下载模板: 'Download Template',
  '*提交前请核实订单状态，不是待发货状态订单无法加入发货单': '*Please verify the status of the order before submission, not to be shipped orders can not be added to the shipping order',
  '第一步: 下载模板': 'Step 1: Download Template',
  '第二步: 上传模板': 'Step 2: Upload the template',
  导出订单详情: 'Export order details',
  新增模板: 'New Template',
  确定导出: 'Determine export',
  批量认领: 'Bulk claiming',
  导出记录: 'Exporting records',
  认领人: 'Adopter',
  申报信息: 'Filing Information',
  上门取件: 'Door-to-door pickup',
  第三方对接状态: 'Third party docking status',
  设置默认值: 'Set default value',
  待对接: 'To be docked',
  对接中: 'Docking in progress',
  对接成功: 'Successful docking',
  对接失败: 'Docking failure',
  预约时间: 'Appointment Time',
  待取件: 'Pending Pickup',
  转运中: 'In Transit',
  预约单号: 'Reservation Order Number',
  取件单号: 'Pick-up order number',
  取件城市: 'Pickup City',
  取件电话: 'Pickup Phone',
  取件姓名: 'Pickup Name',
  设为审核: 'Set as review',
  设置转运单号: 'Set Forwarding Order Number',
  '支持图片格式：jpeg.png.jpg... 图片大小限2M，最多上传3张': 'Supported image formats: jpeg.png.jpg... Image size is limited to 2M, maximum 3 images can be uploaded',
  请选择目的地: 'Please select a destination',
  '请输入名称，字数限制在五十个字内': 'Please enter a name and limit the number of words to fifty',
  包裹日志: 'Parcel Log',
  盘点记录: 'Inventory records',
  所属用户: 'Affiliated Users',
  导出日志: 'Export Log',
  所属客户: 'Affiliated Customers',
  操作类型: 'Operation Type',
  拣货包裹: 'Parcel picking',
  包裹变更: 'Package Change',
  APP签收: 'APP sign-off',
  包裹上架: 'Packages on the shelf',
  盘点单号: 'Inventory single number',
  盘点仓库: 'Inventory warehouse',
  盘点进度: 'Inventory progress',
  按会员ID: 'By Member ID',
  '请输入国家/地区（中）': 'Please enter country/region (in)',
  '国家/地区：': 'Country/Region.：',
  是否同行货: 'Whether peer goods',
  每单固定金额: 'Fixed amount per order',
  按重量或体积重量: 'By weight or volume weight',
  计重方式: 'Weighting method',
  首重佣金: 'First Heavy Commission',
  续重佣金: 'Refill Commission',
  '*每单订单佣金数额': '*Commission amount per order',
  开启多箱计佣: 'Open multiple commissions',
  编号: 'Number',
  '勾选时，如一个订单为多箱发货，则以每箱计佣；不勾选时，则每个订单计佣': 'When checked, if an order is shipped in multiple boxes, the commission will be charged per box; when unchecked, the commission will be charged per order',
  转运须知: 'Transit Instructions',
  合箱须知: 'Instructions for closing the box',
  预设打包箱: 'Preset packing boxes',
  收件地址配置: 'Receiving address configuration',
  打包改价配置: 'Package to change the price of the configuration',
  上门取件配置: 'Door-to-door pickup configuration',
  入库自动生成包裹编号: 'Automatic parcel number generation for inbound storage',
  '*支付类型名称': '*Payment Type Name',
  提示名称: 'Tip Name',
  上传收款二维码: 'Upload the receipt QR code',
  结算时显示汇率转换后价格: 'Exchange rate conversion price displayed during settlement',
  '仅新增显示，方便审核收款与核对账目，不改变系统结算数据': 'Only new displays are added to facilitate the audit of collections and reconciliation of accounts, without changing the system settlement data',
  当前结算货币为: 'The current settlement currency is',
  汇率转换显示: 'Exchange rate conversion display',
  '获取实时汇率（以客户提交支付汇率为准）': 'Access to real-time exchange rates (based on customer submission of payment rates)',
  固定汇率: 'Fixed Exchange Rates',
  请输入转换汇率: 'Please enter the conversion rate',
  沙盒模式: 'Sandbox mode',
  账号: 'Account Number',
  '提示系统仅支持三级区域，对上一级地址操作启用关闭或删除时对下级所有区域生效': 'Tip the system only supports three levels of areas, the upper level of address operations to enable the closure or deletion of all areas in the lower level effective',
  添加二级区域不要选择此项: 'Do not select this item when adding secondary areas',
  添加三级区域不要选择此项: 'Do not select this item when adding tertiary areas',
  子区域: 'Sub-region',
  '*中文名称': '*Chinese Name',
  '*邮编': '*Zip code',
  区域代码: 'Area Code',
  API值: 'API Value',
  与中文名称相同: 'Same name as Chinese',
  '主要用于第三方API的需要，如果不清楚请默认填写与中文一致': 'Mainly used for the needs of the third-party API, if not clear, please fill in the default with the Chinese',
  请选择区域: 'Please select a region',
  "*国家": '*Country',
  耗材名称: 'Consumables Name',
  成本: 'Cost',
  请输入箱子名称: 'Please enter the name of the box',
  请输入长: 'Please enter the length',
  请输入高: 'Please enter high',
  请输入宽: 'Please enter the width',
  允许后台删除收件人地址: 'Allow background deletion of recipient addresses',
  开启收件人地址审核: 'Turn on recipient address audit',
  桌面端打包改价配置: 'Desktop package price change configuration',
  不允许桌面端提交打包: 'Do not allow desktop submissions to be packaged',
  开启后桌面端只允许保存: 'When enabled, the desktop side only allows saving',
  不允许桌面端改价: 'Desktop price change is not allowed',
  开启后桌面端不允许改价: 'No price change is allowed on the desktop after opening',
  APP端打包改价配置: 'APP side package price change configuration',
  不允许运营APP端提交打包: 'Do not allow the operation APP side to submit the package',
  开启后APP端只允许保存: 'After turning on the APP side only allows saving',
  不允许运营APP端改价: 'Not allowed to operate the APP side of the price change',
  开启后运营APP端不允许改价: 'After opening the operation APP side is not allowed to change the price',
  可上门取件日期: 'Pick-up dates available',
  可预约未来时间: 'Appointments can be made for future times',
  当天最早可预约时间: 'Earliest available appointment time on the same day',
  选择时间: 'Select time',
  当天截止最晚预约时间: 'Same day deadline for reservation',
  周一: 'Monday',
  周二: 'Tuesday',
  周三: 'Wednesday',
  周四: 'Thursday',
  周五: 'Friday',
  周六: 'Saturday',
  周日: 'Sunday',
  '*客户编号': '*Customer Number',
  请输入客户编号: 'Please enter the customer number',
  '*充值金额': '*Recharge amount',
  '*充值方式': '*Recharge method',
  '*转账账户': '*Transfer Account',
  转账备注: 'Transfer Remarks',
  上传截图: 'Upload screenshots',
  是否退款充值: 'Whether to refund recharge',
  是否审核: 'Whether to review',
  订单补款: 'Order replenishment',
  待付款: 'Payment pending',
  创建补款单: 'Create a replenishment order',
  补款方式设置: 'Repayment method setting',
  实付金额: 'Actual amount paid',
  请选择付款状态: 'Please select payment status',
  请选择付款方式: 'Please select a payment method',
  补款类型: 'Retroactive payment type',
  补款金额: 'Amount of retroactive payment',
  请选择可用收款方式: 'Please select an available payment method',
  确认支付金额: 'Confirm payment amount',
  代理ID: 'Proxy ID',
  申请金额: 'Application amount',
  请输入内容: 'Please enter content',
  收支记录: 'Income and expenditure records',
  '该说明将显示在客户端（小程序/网站），方便客户理解规则': 'The instructions will be displayed on the client side (applet/website) to make it easier for the client to understand the rules',
  等级说明: 'Grade Description',
  用户组: 'User Groups',
  特定等级组: 'Specific grade group',
  客户标签组: 'Customer Tag Group',
  特定客户: 'Specific Customers',
  请输入客户ID: 'Please enter the customer ID',
  转换规则: 'Conversion rules',
  消费转换成长值: 'Consumption conversion growth value',
  不足1成长值部分不累计: 'Less than 1 growth value is not accumulated',
  不足1积分部分不累计: 'Less than 1 point will not be accumulated',
  '计入成长值消费（以实际支付为准）': 'Counted as growth value consumption (subject to actual payment)',
  触发时间: 'Trigger time',
  '订单为该状态时，成长值进入账户': 'When the order is in this status, the growth value is entered into the account',
  '订单为该状态时，积分进入账户': 'When the order is in this status, the points are credited to the account',
  积分有效期: 'Points validity',
  '成长值到账之日起计算，有效期为': 'The growth value is calculated from the date of arrival and is valid for',
  '积分到账之日起计算，有效期为': 'Points are calculated from the date of arrival and are valid for',
  收入详情: 'Revenue Details',
  新用户福利: 'New User Benefits',
  用户: 'User',
  抵用券详细: 'Coupon Details',
  分类管理: 'Category Management',
  渠道分类: 'Channel Classification',
  '小程序/H5轮播图管理': 'Applet/H5 Rotating image management',
  '小程序/H5海报管理': 'Applet/H5 Poster Management',
  '小程序/H5页面广告管理': 'Applet/H5 page ad management',
  弹窗广告管理: 'Pop-up Ads Management',
  '*广告图名称': '*Name of advertising image',
  请输入广告图名称: 'Please enter the name of the ad image',
  '*上传广告图': '*Upload ad image',
  '*所属应用': '*Applications',
  请选择所属应用: 'Please select the application to which you belong',
  广告类型: 'Ad Type',
  请选择广告类型: 'Please select the type of advertisement',
  '*跳转方式': '*Jump method',
  请选择跳转方式: 'Please select the jumping method',
  内部跳转: 'Internal Jump',
  请选择内部跳转: 'Please select internal jump',
  '*内部url': '*Internal url',
  '*外部url': '*External url',
  请输入外部url: 'Please enter the external url',
  '*公众号文章url': '*Public article url',
  '*显示位置': '*Show Location',
  请选择显示位置: 'Please select the display location',
  '*广告类型': '*Ad Type',
  '建议尺寸：710px * 400px': 'Recommended size: 710px * 400px',
  '建议尺寸：690px * 168px': 'Recommended size: 690px * 168px',
  背景色选择: 'Background color selection',
  '背景图像上传最多不超过五张，建议尺寸750px*1334px': 'Upload up to five background images, recommended size 750px*1334px',
  修改广告图: 'Modify the ad image',
  '建议尺寸：355px*160px': 'Recommended size: 355px*160px',
  '建议尺寸：612px*542px': 'Recommended size: 612px*542px',
  '建议尺寸：710px*120px': 'Recommended size: 710px*120px',
  '建议尺寸：750px*480px': 'Recommended size: 750px*480px',
  'H5登录/注册页': 'H5 login/registration page',
  添加弹窗广告图: 'Add a pop-up ad image',
  修改弹窗广告图: 'Modify the pop-up ad image',
  已结束: 'Closed',
  已取消: 'Canceled',
  新增拼团: 'New Combination',
  发起拼团成员: 'Initiating Combination members',
  拼团仓库: 'Combined Warehouse',
  请输入拼团名称: 'Please enter the name of the group',
  收货地址: 'Receiving Address',
  选择地址: 'Select Address',
  拼团渠道: 'Grouping channels',
  派送形式: 'Dispatch form',
  自提点收货: 'Self-pickup point collection',
  拼团持续时间: 'Grouping Duration',
  填写天数: 'Fill in the number of days',
  是否为公开拼团: 'Whether is an open group purchase',
  拼团介绍: 'Group Purchase Introduction',
  请输入拼团介绍: 'Please enter the group introduction',
  上传拼团封面图: 'Upload group cover image',
  拼图详细: 'Group Purchase Details',
  拼团中: 'In the group buy',
  拼团结束: 'Group buy ends',
  拼团时间剩余: 'Group buy time remaining',
  拼团时间已结束: 'Group buy time has ended',
  修改拼团: 'Modify Group Purchase',
  延长时间: 'Extension time',
  团长有话说: 'Mission Director has something to say',
  寄: 'send',
  收: 'Receive',
  拼团成员: 'Group Buyers',
  添加拼团成员: 'Add a group buy member',
  头像: 'Avatar',
  管理包裹: 'Managing packages',
  提交拼团订单: 'Submit Group Purchase Order',
  昵称: 'Nickname',
  选择渠道: 'Select Channel',
  发布: 'Release',
  时效: 'Statute of limitations',
  '支持格式：.doc .docx .pdf，单个文件不能超过3MB': 'Supported formats: .doc .docx .pdf, individual files cannot exceed 3MB',
  问答管理: 'Question and Answer Management',
  回复: 'Reply',
  删除提问: 'Delete Question',
  展开: 'Open',
  收起: 'Put away',
  '*语言': '*Language',
  新增字符串: 'Add string',
  'H5/小程序': 'H5/applet',
  采购: 'Purchasing',
  采购单: 'Purchase Orders',
  分货转运单: 'Distribution of goods forwarding orders',
  草稿: 'sketch',
  新增采购单: 'Add a new purchase order',
  提交采购: 'Submit a Purchase',
  批量回退: 'Batch rollback',
  PO单号: 'PO order number',
  PO单名称: 'PO list name',
  采购仓库: 'Purchasing Warehouse',
  发货物流公司: 'Shipping Logistics Company',
  发货物流单号: 'Shipping logistics bill number',
  采购总金额: 'Total purchase amount',
  '采购总件/总箱数': 'Total pieces purchased/total cases',
  请输入采购单号: 'Please enter the purchase order number',
  请输入发货物流单号: 'Please enter the shipping logistics number',
  确认发货: 'Confirm Shipping',
  添加发货信息: 'Add shipping information',
  发货公司: 'Shipping Company',
  收货仓库: 'Receiving warehouse',
  发货信息: 'Shipping Information',
  PO单号名称: 'PO order number name',
  采购备注: 'Purchase Remarks',
  采购清单: 'Purchase List',
  商品编号: 'Item number',
  物品中文名称: 'Chinese name of the item',
  物品英文名称: 'English name of the item',
  包装: 'Packaging',
  颜色: 'Color',
  物品明细数量: 'Number of item details',
  物品总箱数: 'Total number of boxes of items',
  添加商品: 'Add product',
  修改商品: 'Modify product',
  中文名称: 'Chinese Name',
  英文名称: 'English Name',
  应到数量: 'Number due',
  装箱数: 'Number of boxes',
  请选择发货公司: 'Please select shipping company',
  请输入物流单号: 'Please enter the logistics bill number',
  编辑采购单: 'Edit Purchase Order',
  采购单详情: 'Purchase Order Details',
  采购单详细: 'Purchase Order Details',
  导出明细表: 'Export Schedule',
  拣货数量: 'Number of picking',
  打包数量: 'Packing quantity',
  拣货差异数量: 'Number of picking discrepancies',
  打包差异数量: 'Number of packing differences',
  日期: 'Date',
  采购详情: 'Purchase details',
  采购单价: 'Purchase unit price',
  物品总数量: 'Total number of items',
  总箱数: 'Total number of boxes',
  确认收货: 'Confirm receipt of goods',
  分货完成: 'Distribution completed',
  您确认分货完成吗: 'Do you confirm that the distribution is complete?',
  转运状态: 'Transit Status',
  分货清单: 'Distribution list',
  分货数量: 'Quantity of distribution',
  下单渠道: 'Order Channels',
  新建分货方案: 'Newly built distribution program',
  分货号: 'Sub-case number',
  分货方案名称: 'Name of distribution program',
  待拣货: 'Pending picking',
  待打包: 'To be packed',
  已转运: 'Transferred',
  打包进度: 'Packing progress',
  包含采购单: 'Includes purchase orders',
  '预计分货(商品数/订单)': 'Estimated distribution (number of items/order)',
  实际拣货: 'Actual picking',
  方案备注: 'Program Remarks',
  上传记录: 'Upload Record',
  导入分货方案: 'Importing Distribution Solutions',
  开始拣货: 'Start picking',
  请选择箱号: 'Please select box number',
  请输入或扫入条码: 'Please enter or scan in the barcode',
  确认: 'Confirmation',
  请扫描拣货单号及条码: 'Please scan the pick list number and barcode',
  拣货单号: 'Pick Order Number',
  已扫描: 'Scanned',
  未扫描: 'Not scanned',
  绿色为拣货数量等于分货数量: 'Green is the number of picks equal to the number of distributions',
  黄色为拣货数量不等于分货数量: 'Yellow is the number of picking not equal to the number of distribution',
  白色为拣货数量为0: 'White is picking quantity is 0',
  品名: 'Name',
  条码: 'barcode',
  分货: 'Distribution of goods',
  拣货: 'Picking',
  拣货完成: 'Picking completed',
  开始打包: 'Start packing',
  请选择订单号: 'Please select the order number',
  收货点: 'Collection point',
  采购编号: 'Purchase number',
  装箱: 'Packing',
  请输入分货号: 'Please enter the sub-item number',
  单页管理: 'Single Page Management',
  区块管理: 'Block Management',
  新增单页: 'New single page',
  编辑单页: 'Editorial single page',
  编辑区块: 'Edit Block',
  开发者id: 'Developer id',
  'AppId(小程序ID)': 'AppId(Applet ID)',
  'AppSecret(小程序密钥)': 'AppSecret(Applet Key)',
  小程序token: 'Applet token',
  请输入小程序token: 'Please enter the applet token',
  请输入aes_key: 'Please enter aes_key',
  PC端配置: 'PC configuration',
  H5链接: 'H5 Link',
  '主要用于集运插件识别（非常重要,多个用英文逗号切分，例如http.www.baidu.com,http.www.google.com': 'Mainly used for consolidation plug-in identification（Very important, more than one is separated by a comma, for example：http.www.baidu.com,http.www.google.com',
  网站ID: 'Site ID',
  网站Secret: 'Website Secret',
  pc端客服二维码: 'pc-side customer service QR code',
  'API与服务*': 'APIs and Services*',
  自定义后台系统: 'Customized back office system',
  后台域名: 'Backend Domain',
  '需登录域名购买平台,对域名进行解析: 将该域名 CNAME 解析到 8.haiouoms.com, 解析后再将域名填入': 'You need to login to the domain name purchase platform and resolve the domain name: Resolve the domain name CNAME to 8.haiouoms.com, After resolving the domain name, fill in the',
  请输入解析后的域名: 'Please enter the resolved domain name',
  查看示例: 'View Example',
  页面标题: 'Page Title',
  页面logo: 'Page logo',
  登录页标题: 'Login Page Title',
  请输入页面标题: 'Please enter a page title',
  登录页logo: 'Login page logo',
  登录页广告图: 'Login page ad image',
  导航栏名称: 'Navigation bar name',
  请输入导航栏展示系统名称: 'Please enter the name of the navigation bar display system',
  导航栏图标: 'Navigation bar icon',
  预报快递公司: 'Forecast Courier',
  请输入新增值服务名称: 'Please enter the name of the new value-added service',
  请输入价格: 'Please enter the price',
  排序索引: 'Sort Index',
  启用状态: 'Enable Status',
  到件先知: 'To the piece prophet',
  登录账号: 'Login Account',
  到件先知状态: 'Arrival Prophet Status',
  轨迹替换: 'Track Replacement',
  '*公司名称': '*Company Name',
  '*快递公司代码': '*Courier company code',
  到件先知即提前获取没有预报信息: 'Arrival foresight means getting no forecast information in advance',
  直接通过快递过来的包裹信息: 'Parcel information directly from the courier',
  快递公司登录账号: 'Courier Company Login Account',
  快递公司登录密码: 'Courier Company Login Password',
  编辑属性: 'Edit Properties',
  '属性名称: ': 'Property Name: ',
  运营: 'Operations',
  客服事务处理:'Customer Service',
  客户管理:'Client Management',
  员工管理:'Staff Management',
  基础数据:'Basic Data',
  仓库地址管理:'Warehouse Address Management',
  渠道路线配置:'Channel Route Configuration',
  订单管理:'Order Management',
  预报包裹:'Forecast Packages',
  货站管理:'Freight Station Management',
  快速入库:'Quick Entry',
  自提点管理:'Self-pickup point management',
  余额扣款:'Balance debit',
  流水管理:'Flow Management',
  数据概览:'Data Overview',
  营销报表:'Marketing Statement',
  语言配置:'Language Configuration',
  创建模板:'Create Template',
  模板名称:'Template Name',
  模板尺寸:'Template Size',
  是否自定义模板:'Whether to customize the template',
  面单配置:'Face sheet configuration',
  仓位概览:'Position Overview',
  货架详细:'Shelf details',
  货位:'Cargo space',
  上架时间:'Shelf time',
  上架人:'Uploader',
  货物属性:'Cargo properties',
  欢迎使用海鸥集运系统:'Welcome to Seagull System',
  北京时间:'Beijing Time',
  欧州中部时间:'Central European Time',
  待签收包裹:'Package to be signed for',
  正常预报:'Normal Forecast',
  待打包包裹:'Package to be packed',
  待发货包裹:'Package to be shipped',
  待财务审核:'Pending financial review',
  上次登录时间:'Last login time',
  上次登录IP:'Last login IP',
  修改个人资料:'Modify personal information',
  注销账号:'Cancellation of account',
  实况概括:'Factual Overview',
  更新于:'Updated in',
  隐藏数据:'Hidden Data',
  复制数据:'Copy data',
  今日新增用户:'New users today',
  昨日:'Yesterday',
  本月新增用户:'New users this month',
  今日收入:"Today's Revenue",
  今日优惠:"Today's Offer",
  今日支付金额:"Today's payment amount",
  今日充值金额:"Today's top-up amount",
  今日产能:"Today's capacity",
  上架:'Uploaded',
  投诉数:'Number of complaints',
  订单评价:'Order Evaluation',
  问题件列表:'List of problem pieces',
  会员编号:'Membership Number',
  包裹号:'Parcel number',
  货物状态:'Cargo Status',
  问题描述:'Problem Description',
  注册用户数:'Number of registered users',
  邮箱激活数:'Number of mailbox activations',
  手机号激活数:'Number of cell phone number activation',
  预报量:'Forecast volume',
  转化率:'Conversion rate',
  优惠券:'Coupons',
  仓位使用:'Position usage',
  终端软件下载:'Terminal Software Download',
  '使用手机、桌面端集运业务':'Use of cell phones, desktop shipping business',
  海鸥集运系统操作使用手册:'Hai-O System Operation Manual',
  '关注【通晓科技】':'Follow 【Tongxiao Technology】',
  '分享操作技巧、集运运营干货':'Share operation skills, shipping and operation tips',
  美东时间:'American eastern time',
  已生成:'Generated',
  已发放:'Issued',
  已使用:'Used',
  已过期:'Expired',
  已生成仓位:'Generated Positions',
  已使用仓位:'Used Positions',
  已上架包裹:'Shelved packages',
  已超期包裹:'Overdue package',
  系统:'System',
  偏远地区查询:'Remote Area Search',
  '注意! 由于FEDEX， DHL，UPS，TNT偏远地区更新频繁，系统内置的偏远数据仅作参考查询， 最终以FEDEX， DHL， UPS， TNT官方为准。如有疑问建议直接致电对应的官方客服电话查询核实，请知悉':'Attention! As FEDEX, DHL, UPS, TNT remote areas are updated frequently, the remote data built into the system is for reference only, the final official FEDEX, DHL, UPS, TNT shall prevail. If you have any questions, please call the corresponding official customer service number for verification.',
  偏远类型:'Remote Type',
  国家地区编码:'Country area code',
  国家地区名称:'Country Name',
  起始邮编:'Starting Postcode',
  截止邮编:'Deadline Postcode',
  偏远等级:'Remote grade',
  来源:'Source',
  快速入库下单:'Quick Entry Order Placement',
  物品状态:'Item Status',
  上大货专区:'On the big goods area',
  '请输入客户ID,不填则默认无人认领':'Please enter the customer ID, do not fill in the default unclaimed',
  下单方式:'Order Method',
  集齐再发:'Collect all and send again',
  到件即发:'Delivery on arrival',
  当前件数:'Current number of pieces',
  AI内容助手:'AI Content Assistant',
  海鸥AI文案助手:'Hai-O AI Copywriting Assistant',
  '请输入: 类似于帮我写一篇类似于中国到美国的集运转运的软文 (Shift + Enter = 换行)':'Please type: Something like Help me write a soft copy of something like China to US consolidation transit (Shift + Enter = line break)',
  财务审核:'Financial Audit',
  偏远地区设置:'Remote Area Setting',
  最后更新时间:'Last update time',
  修改偏远信息:'Modify remote information',
  偏远备注:'Remote Remarks',
  '国家/地区二字码':'Country/region code',
  '国家/地区名称':'Name of country/region',
  '提示: 编辑明细前请先保存偏远类型信息。系统内置偏远信息不可修改，若发现系统偏远信息有误，请及时与软件供应商联系更新修复，谢谢合作。':'Tip: Please save the remote type information before editing the details. If you find that the system remote information is wrong, please contact the software supplier to update and fix it in time, thank you for your cooperation.',
  结束邮编:'End Zip Code',
  最新更新时间:'Latest update time',
  添加偏远信息:'Add remote information',
  预留订单号:'Reserved order number',
  导入清单:'Import List',
  开始单号:'Start single number',
  结束单号:'End order number',
  生成数量:'Number of Generated',
  可用数量:'Available Quantity',
  使用单号:'Use of single number',
  作废单号:'Invalid order number',
  模板:'Template',
  标准模板:'Standard Template',
  预留单号:'Reserved Order Number',
  预留袋号:'Reserved bag number',
  请输入批次号或单号进行查询:'Please enter the batch number or order number to inquire',
  上传模板:'Upload Template',
  台湾模板:'Taiwan Template',
  预留袋号:'Reserved bag number',
  通关专区:'Pass Area',
  报关业者:'Customs broker',
  单号总量:'Total number of single',
  作废数量:'Number of scraps',
  对应订单号:'Corresponding order number',
  退出登录:'Log out of login',
  去处理:'To handle',
  收发区域:'Sending and receiving area',
  清单:'inventory',
  先知:'Knowing in advance',
  异常件列表:'List of abnormal parts',
  折扣类型:'Discount Type',
  最低重量:'最低重量',
  待使用数量:'待使用数量',
  兑换码管理:'兑换码管理',
  路线类型:'路线类型',
  自动签收配置:'自动签收配置',
  开始自动签收:'开始自动签收',
  隔天生效:'隔天生效',
  发货后触发自动签收时间:'发货后触发自动签收时间',
  货到付款的不能签收不能少于7天:'货到付款的不能签收不能少于7天',
  签收后是否自动评价:'签收后是否自动评价',
  开启自动评价功能后会触发自动返券积分成长值事件:'开启自动评价功能后会触发自动返券积分成长值事件',
  自动评价内容:'自动评价内容',
  自动评价评分:'自动评价评分',
}
